// Code generated by go run ./scripts/contracts -write. DO NOT EDIT.

package openrails

// The level groups.
const (
	// MerchantConfig is every route of Routes.MerchantConfig, reads included: the merchant's own configuration.
	MerchantConfig RouteSet = "merchant_config"
	// StaffReads is every read of Routes.Merchant: staff looking at customers' billing.
	StaffReads RouteSet = "staff_reads"
	// StaffWrites is every write of Routes.Merchant: staff acting on customers' billing.
	StaffWrites RouteSet = "staff_writes"
)

// The resource groups: a guard on one overrides its routes' level group.
const (
	// Access covers ListCustomerEntitlements, ListEntitlementCustomers, CheckEntitlements, GetEffectiveTiers, CheckProductAccess, ListProductAccess, CreateProductAccess, DeleteProductAccess.
	Access RouteSet = "resource:access"
	// BillingData covers ExportBillingArchive, ImportBillingArchive, ImportBilling.
	BillingData RouteSet = "resource:billing_data"
	// Catalog covers GetCatalogRevision, ApplyCatalog, ReplaceEntitlements, ListCatalogDrift, RefreshCatalogDrift, ListMeters, GetMeter, SetMeter, SetMeterRateCard, DeleteMeterRateCard, ListMeterRateOverrides, ListRateOverrides, SetRateOverride, DeleteRateOverride, ArchiveProduct, GetProductArchive, AskCatalog, CreateProduct, ListProducts, GetProduct, UpdateProduct, GetProductByKey, EnsureProduct, CreatePrice, ListPrices, GetPrice, UpdatePrice, GetPriceByKey, ListPriceKeyHistory, ListOffers.
	Catalog RouteSet = "resource:catalog"
	// Checkout covers GetCheckoutConfig.
	Checkout RouteSet = "resource:checkout"
	// CheckoutSessions covers CreateCheckoutSession.
	CheckoutSessions RouteSet = "resource:checkout_sessions"
	// Credits covers CreateCreditGrants, ListCreditGrants, GetCreditGrant, RevokeCreditGrant, ListCreditTransactions, GetBalance, ListSpendDelegations, SetSpendDelegations, DeleteSpendDelegation.
	Credits RouteSet = "resource:credits"
	// CustomerSettings covers ListCustomerSettings, UpdateCustomerSettings.
	CustomerSettings RouteSet = "resource:customer_settings"
	// Customers covers ListCustomers, EnsureCustomers, GetCustomerBillingProfile, ListCustomerDelinquency, ListDelinquency, ListPaymentMethods, DeletePaymentMethod.
	Customers RouteSet = "resource:customers"
	// Dashboard covers SetDashboard, GenerateDashboardWidget.
	Dashboard RouteSet = "resource:dashboard"
	// Findings covers ListFindings, GetFindingSummary, GetFinding, ResolveFinding.
	Findings RouteSet = "resource:findings"
	// HostEvents covers ListHostEvents, AcknowledgeHostEvents.
	HostEvents RouteSet = "resource:host_events"
	// Invoices covers ListInvoices, GetInvoice, ListInvoicePayments, CreateInvoicePayment, VoidInvoice, MarkInvoiceUncollectible, RetryInvoiceCollection.
	Invoices RouteSet = "resource:invoices"
	// Metrics covers QueryMetrics, GetMetricsSchema, GetDashboard, AskMetrics.
	Metrics RouteSet = "resource:metrics"
	// Operations covers ListMerchantNotifications, GetUnreadNotificationCount, MarkNotificationsRead, ListWorkerHealth.
	Operations RouteSet = "resource:operations"
	// PSPs covers ListPSPs, CreatePSP, GetPSP, UpdatePSP, ArchivePSP, PreviewPSPRouting, RefreshPSPs, ListRails.
	PSPs RouteSet = "resource:psps"
	// Payments covers GetProductArchive, GetPaymentSettlementStatus, CreateOffChannelPayment, ListPayments, GetPayment, ListPaymentAttempts, GetPaymentAttempt, ListRebillCycles, GetRebillCycle.
	Payments RouteSet = "resource:payments"
	// Refunds covers ArchiveProduct, RefundPayment.
	Refunds RouteSet = "resource:refunds"
	// Settings covers GetMerchantConfiguration, ApplyMerchantConfiguration, GetAPIHost, SetAPIHost, VerifyAPIHost, ListAlertWebhooks, CreateAlertWebhook, DeleteAlertWebhook, SetAlertWebhookURL.
	Settings RouteSet = "resource:settings"
	// Subscriptions covers ListSubscriptions, GetSubscription, CancelSubscription, ResumeSubscription, ChangeTier, PreviewTierChange, SetSubscriptionPaymentMethod, CreateRepriceBatch, PreviewRepriceBatch, ListRepriceBatches, GetRepriceBatch, CancelRepriceBatch, CreatePlanMigration, PreviewPlanMigration, ListReprices, GetReprice, CancelReprice.
	Subscriptions RouteSet = "resource:subscriptions"
	// Usage covers Admit, GetAdmission, CaptureAdmission, ReleaseAdmissions, ExtendAdmissions, ReportWastedSpend, RecordUsage, GetUsage, OpenOperationAuthorization, ListOperationAuthorizations, GetOperationAuthorization, ExtendOperationAuthorization, ReleaseOperationAuthorization, RecordProviderBillingObservation, GetProviderBillingQualification, ResolveProviderBillingQualification, RefuseProviderBillingQualification, CloseOperationAuthorization, ListProviderBillingQualifications.
	Usage RouteSet = "resource:usage"
)

// One route each, named after its Client method: a guard on one overrides its groups.
const (
	// AcknowledgeHostEvents is POST /v1/merchant/host-events/acknowledge.
	AcknowledgeHostEvents RouteSet = "route:AcknowledgeHostEvents"
	// Admit is POST /v1/merchant/admissions.
	Admit RouteSet = "route:Admit"
	// ApplyCatalog is POST /v1/merchant/catalog/applications.
	ApplyCatalog RouteSet = "route:ApplyCatalog"
	// ApplyMerchantConfiguration is POST /v1/merchant/configuration/applications.
	ApplyMerchantConfiguration RouteSet = "route:ApplyMerchantConfiguration"
	// ArchivePSP is POST /v1/merchant/psps/{id}/archive.
	ArchivePSP RouteSet = "route:ArchivePSP"
	// ArchiveProduct is POST /v1/merchant/catalog/product-archives.
	ArchiveProduct RouteSet = "route:ArchiveProduct"
	// AskCatalog is POST /v1/merchant/catalog/ask.
	AskCatalog RouteSet = "route:AskCatalog"
	// AskMetrics is POST /v1/merchant/metrics/ask.
	AskMetrics RouteSet = "route:AskMetrics"
	// CancelReprice is POST /v1/merchant/reprices/{id}/cancel.
	CancelReprice RouteSet = "route:CancelReprice"
	// CancelRepriceBatch is POST /v1/merchant/reprice-batches/{id}/cancel.
	CancelRepriceBatch RouteSet = "route:CancelRepriceBatch"
	// CancelSubscription is POST /v1/merchant/subscriptions/{id}/cancel.
	CancelSubscription RouteSet = "route:CancelSubscription"
	// CaptureAdmission is POST /v1/merchant/admissions/{request_id}/capture.
	CaptureAdmission RouteSet = "route:CaptureAdmission"
	// ChangeTier is POST /v1/merchant/subscriptions/{id}/change-tier.
	ChangeTier RouteSet = "route:ChangeTier"
	// CheckEntitlements is POST /v1/merchant/customers/{customer_id}/entitlements/check.
	CheckEntitlements RouteSet = "route:CheckEntitlements"
	// CheckProductAccess is POST /v1/merchant/customers/{customer_id}/product-access/check.
	CheckProductAccess RouteSet = "route:CheckProductAccess"
	// CloseOperationAuthorization is POST /v1/merchant/provider-operations/{operation_id}/close.
	CloseOperationAuthorization RouteSet = "route:CloseOperationAuthorization"
	// CreateAlertWebhook is POST /v1/merchant/alert-webhooks.
	CreateAlertWebhook RouteSet = "route:CreateAlertWebhook"
	// CreateCheckoutSession is POST /v1/merchant/checkout-sessions.
	CreateCheckoutSession RouteSet = "route:CreateCheckoutSession"
	// CreateCreditGrants is POST /v1/merchant/credit-grants.
	CreateCreditGrants RouteSet = "route:CreateCreditGrants"
	// CreateInvoicePayment is POST /v1/merchant/invoices/{id}/payments.
	CreateInvoicePayment RouteSet = "route:CreateInvoicePayment"
	// CreateOffChannelPayment is POST /v1/merchant/customers/{customer_id}/payments/off-channel.
	CreateOffChannelPayment RouteSet = "route:CreateOffChannelPayment"
	// CreatePSP is POST /v1/merchant/psps.
	CreatePSP RouteSet = "route:CreatePSP"
	// CreatePlanMigration is POST /v1/merchant/plan-migrations.
	CreatePlanMigration RouteSet = "route:CreatePlanMigration"
	// CreatePrice is POST /v1/merchant/catalog/prices.
	CreatePrice RouteSet = "route:CreatePrice"
	// CreateProduct is POST /v1/merchant/catalog/products.
	CreateProduct RouteSet = "route:CreateProduct"
	// CreateProductAccess is POST /v1/merchant/product-access.
	CreateProductAccess RouteSet = "route:CreateProductAccess"
	// CreateRepriceBatch is POST /v1/merchant/reprice-batches.
	CreateRepriceBatch RouteSet = "route:CreateRepriceBatch"
	// DeleteAlertWebhook is DELETE /v1/merchant/alert-webhooks/{id}.
	DeleteAlertWebhook RouteSet = "route:DeleteAlertWebhook"
	// DeleteMeterRateCard is DELETE /v1/merchant/catalog/meters/{key}/rate-card.
	DeleteMeterRateCard RouteSet = "route:DeleteMeterRateCard"
	// DeletePaymentMethod is DELETE /v1/merchant/customers/{customer_id}/payment-methods/{id}.
	DeletePaymentMethod RouteSet = "route:DeletePaymentMethod"
	// DeleteProductAccess is DELETE /v1/merchant/customers/{customer_id}/product-access/{id}.
	DeleteProductAccess RouteSet = "route:DeleteProductAccess"
	// DeleteRateOverride is DELETE /v1/merchant/customers/{customer_id}/rate-overrides/{meter_key}.
	DeleteRateOverride RouteSet = "route:DeleteRateOverride"
	// DeleteSpendDelegation is DELETE /v1/merchant/customers/{customer_id}/spend-delegations/{scope}/{scope_key}.
	DeleteSpendDelegation RouteSet = "route:DeleteSpendDelegation"
	// EnsureCustomers is POST /v1/merchant/customers/ensure.
	EnsureCustomers RouteSet = "route:EnsureCustomers"
	// EnsureProduct is PUT /v1/merchant/catalog/products/by-key/{product_key}.
	EnsureProduct RouteSet = "route:EnsureProduct"
	// ExportBillingArchive is GET /v1/merchant/billing-archive.
	ExportBillingArchive RouteSet = "route:ExportBillingArchive"
	// ExtendAdmissions is POST /v1/merchant/admissions/extend.
	ExtendAdmissions RouteSet = "route:ExtendAdmissions"
	// ExtendOperationAuthorization is POST /v1/merchant/provider-operations/{operation_id}/extend.
	ExtendOperationAuthorization RouteSet = "route:ExtendOperationAuthorization"
	// GenerateDashboardWidget is POST /v1/merchant/dashboard/widgets/generate.
	GenerateDashboardWidget RouteSet = "route:GenerateDashboardWidget"
	// GetAPIHost is GET /v1/merchant/api-host.
	GetAPIHost RouteSet = "route:GetAPIHost"
	// GetAdmission is GET /v1/merchant/admissions/{request_id}.
	GetAdmission RouteSet = "route:GetAdmission"
	// GetBalance is GET /v1/merchant/customers/{customer_id}/balance.
	GetBalance RouteSet = "route:GetBalance"
	// GetCatalogRevision is GET /v1/merchant/catalog/revision.
	GetCatalogRevision RouteSet = "route:GetCatalogRevision"
	// GetCheckoutConfig is GET /v1/merchant/checkout-config.
	GetCheckoutConfig RouteSet = "route:GetCheckoutConfig"
	// GetCreditGrant is GET /v1/merchant/customers/{customer_id}/credit-grants/{id}.
	GetCreditGrant RouteSet = "route:GetCreditGrant"
	// GetCustomerBillingProfile is GET /v1/merchant/customers/{customer_id}/billing-profile.
	GetCustomerBillingProfile RouteSet = "route:GetCustomerBillingProfile"
	// GetDashboard is GET /v1/merchant/dashboard.
	GetDashboard RouteSet = "route:GetDashboard"
	// GetEffectiveTiers is POST /v1/merchant/tiers/lookup.
	GetEffectiveTiers RouteSet = "route:GetEffectiveTiers"
	// GetFinding is GET /v1/merchant/findings/{id}.
	GetFinding RouteSet = "route:GetFinding"
	// GetFindingSummary is GET /v1/merchant/findings/summary.
	GetFindingSummary RouteSet = "route:GetFindingSummary"
	// GetInvoice is GET /v1/merchant/invoices/{id}.
	GetInvoice RouteSet = "route:GetInvoice"
	// GetMerchantConfiguration is GET /v1/merchant/configuration.
	GetMerchantConfiguration RouteSet = "route:GetMerchantConfiguration"
	// GetMeter is GET /v1/merchant/catalog/meters/{key}.
	GetMeter RouteSet = "route:GetMeter"
	// GetMetricsSchema is GET /v1/merchant/metrics/schema.
	GetMetricsSchema RouteSet = "route:GetMetricsSchema"
	// GetOperationAuthorization is GET /v1/merchant/provider-operations/{operation_id}.
	GetOperationAuthorization RouteSet = "route:GetOperationAuthorization"
	// GetPSP is GET /v1/merchant/psps/{id}.
	GetPSP RouteSet = "route:GetPSP"
	// GetPayment is GET /v1/merchant/payments/{id}.
	GetPayment RouteSet = "route:GetPayment"
	// GetPaymentAttempt is GET /v1/merchant/payment-attempts/{id}.
	GetPaymentAttempt RouteSet = "route:GetPaymentAttempt"
	// GetPaymentSettlementStatus is GET /v1/merchant/customers/{customer_id}/payment-settlement-status.
	GetPaymentSettlementStatus RouteSet = "route:GetPaymentSettlementStatus"
	// GetPrice is GET /v1/merchant/catalog/prices/{id}.
	GetPrice RouteSet = "route:GetPrice"
	// GetPriceByKey is GET /v1/merchant/catalog/products/by-key/{product_key}/prices/by-key/{key}.
	GetPriceByKey RouteSet = "route:GetPriceByKey"
	// GetProduct is GET /v1/merchant/catalog/products/{id}.
	GetProduct RouteSet = "route:GetProduct"
	// GetProductArchive is GET /v1/merchant/catalog/product-archives/{id}.
	GetProductArchive RouteSet = "route:GetProductArchive"
	// GetProductByKey is GET /v1/merchant/catalog/products/by-key/{product_key}.
	GetProductByKey RouteSet = "route:GetProductByKey"
	// GetProviderBillingQualification is GET /v1/merchant/provider-operations/{operation_id}/qualification.
	GetProviderBillingQualification RouteSet = "route:GetProviderBillingQualification"
	// GetRebillCycle is GET /v1/merchant/rebill-cycles/{id}.
	GetRebillCycle RouteSet = "route:GetRebillCycle"
	// GetReprice is GET /v1/merchant/reprices/{id}.
	GetReprice RouteSet = "route:GetReprice"
	// GetRepriceBatch is GET /v1/merchant/reprice-batches/{id}.
	GetRepriceBatch RouteSet = "route:GetRepriceBatch"
	// GetSubscription is GET /v1/merchant/subscriptions/{id}.
	GetSubscription RouteSet = "route:GetSubscription"
	// GetUnreadNotificationCount is GET /v1/merchant/notifications/unread-count.
	GetUnreadNotificationCount RouteSet = "route:GetUnreadNotificationCount"
	// GetUsage is GET /v1/merchant/customers/{customer_id}/usage.
	GetUsage RouteSet = "route:GetUsage"
	// ImportBilling is POST /v1/merchant/billing-import.
	ImportBilling RouteSet = "route:ImportBilling"
	// ImportBillingArchive is POST /v1/merchant/billing-archive.
	ImportBillingArchive RouteSet = "route:ImportBillingArchive"
	// ListAlertWebhooks is GET /v1/merchant/alert-webhooks.
	ListAlertWebhooks RouteSet = "route:ListAlertWebhooks"
	// ListCatalogDrift is GET /v1/merchant/catalog/drift.
	ListCatalogDrift RouteSet = "route:ListCatalogDrift"
	// ListCreditGrants is GET /v1/merchant/customers/{customer_id}/credit-grants.
	ListCreditGrants RouteSet = "route:ListCreditGrants"
	// ListCreditTransactions is GET /v1/merchant/customers/{customer_id}/transactions.
	ListCreditTransactions RouteSet = "route:ListCreditTransactions"
	// ListCustomerDelinquency is GET /v1/merchant/customers/{customer_id}/delinquency.
	ListCustomerDelinquency RouteSet = "route:ListCustomerDelinquency"
	// ListCustomerEntitlements is GET /v1/merchant/customers/{customer_id}/entitlements.
	ListCustomerEntitlements RouteSet = "route:ListCustomerEntitlements"
	// ListCustomerSettings is GET /v1/merchant/customers/settings.
	ListCustomerSettings RouteSet = "route:ListCustomerSettings"
	// ListCustomers is GET /v1/merchant/customers.
	ListCustomers RouteSet = "route:ListCustomers"
	// ListDelinquency is GET /v1/merchant/delinquency.
	ListDelinquency RouteSet = "route:ListDelinquency"
	// ListEntitlementCustomers is GET /v1/merchant/entitlements/{entitlement}/customers.
	ListEntitlementCustomers RouteSet = "route:ListEntitlementCustomers"
	// ListFindings is GET /v1/merchant/findings.
	ListFindings RouteSet = "route:ListFindings"
	// ListHostEvents is GET /v1/merchant/host-events.
	ListHostEvents RouteSet = "route:ListHostEvents"
	// ListInvoicePayments is GET /v1/merchant/invoices/{id}/payments.
	ListInvoicePayments RouteSet = "route:ListInvoicePayments"
	// ListInvoices is GET /v1/merchant/invoices.
	ListInvoices RouteSet = "route:ListInvoices"
	// ListMerchantNotifications is GET /v1/merchant/notifications.
	ListMerchantNotifications RouteSet = "route:ListMerchantNotifications"
	// ListMeterRateOverrides is GET /v1/merchant/catalog/meters/{key}/rate-overrides.
	ListMeterRateOverrides RouteSet = "route:ListMeterRateOverrides"
	// ListMeters is GET /v1/merchant/catalog/meters.
	ListMeters RouteSet = "route:ListMeters"
	// ListOffers is POST /v1/merchant/catalog/offers/lookup.
	ListOffers RouteSet = "route:ListOffers"
	// ListOperationAuthorizations is GET /v1/merchant/provider-operations.
	ListOperationAuthorizations RouteSet = "route:ListOperationAuthorizations"
	// ListPSPs is GET /v1/merchant/psps.
	ListPSPs RouteSet = "route:ListPSPs"
	// ListPaymentAttempts is GET /v1/merchant/payment-attempts.
	ListPaymentAttempts RouteSet = "route:ListPaymentAttempts"
	// ListPaymentMethods is GET /v1/merchant/customers/{customer_id}/payment-methods.
	ListPaymentMethods RouteSet = "route:ListPaymentMethods"
	// ListPayments is GET /v1/merchant/payments.
	ListPayments RouteSet = "route:ListPayments"
	// ListPriceKeyHistory is GET /v1/merchant/catalog/products/by-key/{product_key}/prices/by-key/{key}/history.
	ListPriceKeyHistory RouteSet = "route:ListPriceKeyHistory"
	// ListPrices is GET /v1/merchant/catalog/prices.
	ListPrices RouteSet = "route:ListPrices"
	// ListProductAccess is GET /v1/merchant/customers/{customer_id}/product-access.
	ListProductAccess RouteSet = "route:ListProductAccess"
	// ListProducts is GET /v1/merchant/catalog/products.
	ListProducts RouteSet = "route:ListProducts"
	// ListProviderBillingQualifications is GET /v1/merchant/provider-qualifications.
	ListProviderBillingQualifications RouteSet = "route:ListProviderBillingQualifications"
	// ListRails is GET /v1/merchant/rails.
	ListRails RouteSet = "route:ListRails"
	// ListRateOverrides is GET /v1/merchant/customers/{customer_id}/rate-overrides.
	ListRateOverrides RouteSet = "route:ListRateOverrides"
	// ListRebillCycles is GET /v1/merchant/rebill-cycles.
	ListRebillCycles RouteSet = "route:ListRebillCycles"
	// ListRepriceBatches is GET /v1/merchant/reprice-batches.
	ListRepriceBatches RouteSet = "route:ListRepriceBatches"
	// ListReprices is GET /v1/merchant/reprices.
	ListReprices RouteSet = "route:ListReprices"
	// ListSpendDelegations is GET /v1/merchant/customers/{customer_id}/spend-delegations.
	ListSpendDelegations RouteSet = "route:ListSpendDelegations"
	// ListSubscriptions is GET /v1/merchant/subscriptions.
	ListSubscriptions RouteSet = "route:ListSubscriptions"
	// ListWorkerHealth is GET /v1/merchant/worker-health.
	ListWorkerHealth RouteSet = "route:ListWorkerHealth"
	// MarkInvoiceUncollectible is POST /v1/merchant/invoices/{id}/uncollectible.
	MarkInvoiceUncollectible RouteSet = "route:MarkInvoiceUncollectible"
	// MarkNotificationsRead is POST /v1/merchant/notifications/read.
	MarkNotificationsRead RouteSet = "route:MarkNotificationsRead"
	// OpenOperationAuthorization is POST /v1/merchant/provider-operations.
	OpenOperationAuthorization RouteSet = "route:OpenOperationAuthorization"
	// PreviewPSPRouting is POST /v1/merchant/psps/routing-preview.
	PreviewPSPRouting RouteSet = "route:PreviewPSPRouting"
	// PreviewPlanMigration is POST /v1/merchant/plan-migrations/preview.
	PreviewPlanMigration RouteSet = "route:PreviewPlanMigration"
	// PreviewRepriceBatch is POST /v1/merchant/reprice-batches/preview.
	PreviewRepriceBatch RouteSet = "route:PreviewRepriceBatch"
	// PreviewTierChange is POST /v1/merchant/subscriptions/{id}/change-tier/preview.
	PreviewTierChange RouteSet = "route:PreviewTierChange"
	// QueryMetrics is POST /v1/merchant/metrics/query.
	QueryMetrics RouteSet = "route:QueryMetrics"
	// RecordProviderBillingObservation is POST /v1/merchant/provider-operations/{operation_id}/observations.
	RecordProviderBillingObservation RouteSet = "route:RecordProviderBillingObservation"
	// RecordUsage is POST /v1/merchant/usage-events.
	RecordUsage RouteSet = "route:RecordUsage"
	// RefreshCatalogDrift is POST /v1/merchant/catalog/drift/refresh.
	RefreshCatalogDrift RouteSet = "route:RefreshCatalogDrift"
	// RefreshPSPs is POST /v1/merchant/psps/refresh.
	RefreshPSPs RouteSet = "route:RefreshPSPs"
	// RefundPayment is POST /v1/merchant/payments/{id}/refunds.
	RefundPayment RouteSet = "route:RefundPayment"
	// RefuseProviderBillingQualification is POST /v1/merchant/provider-operations/{operation_id}/refusal.
	RefuseProviderBillingQualification RouteSet = "route:RefuseProviderBillingQualification"
	// ReleaseAdmissions is POST /v1/merchant/admissions/release.
	ReleaseAdmissions RouteSet = "route:ReleaseAdmissions"
	// ReleaseOperationAuthorization is POST /v1/merchant/provider-operations/{operation_id}/release.
	ReleaseOperationAuthorization RouteSet = "route:ReleaseOperationAuthorization"
	// ReplaceEntitlements is POST /v1/merchant/catalog/entitlement-replacements.
	ReplaceEntitlements RouteSet = "route:ReplaceEntitlements"
	// ReportWastedSpend is POST /v1/merchant/wasted-spend.
	ReportWastedSpend RouteSet = "route:ReportWastedSpend"
	// ResolveFinding is POST /v1/merchant/findings/{id}/resolve.
	ResolveFinding RouteSet = "route:ResolveFinding"
	// ResolveProviderBillingQualification is POST /v1/merchant/provider-operations/{operation_id}/resolution.
	ResolveProviderBillingQualification RouteSet = "route:ResolveProviderBillingQualification"
	// ResumeSubscription is POST /v1/merchant/subscriptions/{id}/resume.
	ResumeSubscription RouteSet = "route:ResumeSubscription"
	// RetryInvoiceCollection is POST /v1/merchant/invoices/{id}/retry-collection.
	RetryInvoiceCollection RouteSet = "route:RetryInvoiceCollection"
	// RevokeCreditGrant is POST /v1/merchant/customers/{customer_id}/credit-grants/{id}/revoke.
	RevokeCreditGrant RouteSet = "route:RevokeCreditGrant"
	// SetAPIHost is PUT /v1/merchant/api-host.
	SetAPIHost RouteSet = "route:SetAPIHost"
	// SetAlertWebhookURL is PUT /v1/merchant/alert-webhooks/{id}/url.
	SetAlertWebhookURL RouteSet = "route:SetAlertWebhookURL"
	// SetDashboard is PUT /v1/merchant/dashboard.
	SetDashboard RouteSet = "route:SetDashboard"
	// SetMeter is PUT /v1/merchant/catalog/meters/{key}.
	SetMeter RouteSet = "route:SetMeter"
	// SetMeterRateCard is PUT /v1/merchant/catalog/meters/{key}/rate-card.
	SetMeterRateCard RouteSet = "route:SetMeterRateCard"
	// SetRateOverride is PUT /v1/merchant/customers/{customer_id}/rate-overrides/{meter_key}.
	SetRateOverride RouteSet = "route:SetRateOverride"
	// SetSpendDelegations is PUT /v1/merchant/customers/{customer_id}/spend-delegations.
	SetSpendDelegations RouteSet = "route:SetSpendDelegations"
	// SetSubscriptionPaymentMethod is PUT /v1/merchant/subscriptions/{id}/payment-method.
	SetSubscriptionPaymentMethod RouteSet = "route:SetSubscriptionPaymentMethod"
	// UpdateCustomerSettings is PATCH /v1/merchant/customers/settings.
	UpdateCustomerSettings RouteSet = "route:UpdateCustomerSettings"
	// UpdatePSP is PATCH /v1/merchant/psps/{id}.
	UpdatePSP RouteSet = "route:UpdatePSP"
	// UpdatePrice is PATCH /v1/merchant/catalog/prices/{id}.
	UpdatePrice RouteSet = "route:UpdatePrice"
	// UpdateProduct is PATCH /v1/merchant/catalog/products/{id}.
	UpdateProduct RouteSet = "route:UpdateProduct"
	// VerifyAPIHost is POST /v1/merchant/api-host/verify.
	VerifyAPIHost RouteSet = "route:VerifyAPIHost"
	// VoidInvoice is POST /v1/merchant/invoices/{id}/void.
	VoidInvoice RouteSet = "route:VoidInvoice"
)
