package routes

import (
	"github.com/open-rails/openrails/billing"
	"github.com/open-rails/openrails/catalog"
	"github.com/open-rails/openrails/internal/api"
	"github.com/open-rails/openrails/internal/http/handlers"
	"github.com/open-rails/openrails/internal/http/middleware"
	"github.com/open-rails/openrails/internal/modules/copilot"
	"github.com/open-rails/openrails/internal/service"
)

// catalogRoutes is what a merchant sells: products, prices, usage meters and
// their rate cards. The public pair lists what a buyer may see; the merchant
// routes administer one catalog; /v1/catalog is a creator managing its own.
// A write is mounted only where the deployment allows catalog updates.
var catalogRoutes = []Route{
	{Method: GET, Path: "/v1/products", Group: Checkout, Auth: AuthOptional,
		Query: queryOf(handlers.GetProductsQuery{}), Responses: []Reply{{200, api.List[api.ProductObject]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.GetProducts)},
	{Method: GET, Path: "/v1/prices", Group: Checkout, Auth: AuthOptional,
		Query: queryOf(handlers.GetPricesQuery{}), Responses: []Reply{{200, api.List[api.PriceObject]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.GetPrices)},
	{Method: GET, Path: "/v1/merchant/customers/{customer_id}/rate-overrides", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead,
		Responses: []Reply{{200, []service.PayerRateCardDTO{}}}, Errors: codes("invalid_param"), Handler: h(handlers.ListAdminRateOverrides)},
	{Method: PUT, Path: "/v1/merchant/customers/{customer_id}/rate-overrides/{meter_key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsUpdate, Limit: middleware.AdminOperationGrant, CatalogWrite: true,
		Request: handlers.AdminRateOverrideRequest{}, Responses: []Reply{{200, service.PayerRateCardDTO{}}}, Errors: codes("invalid_param"), Handler: h(handlers.PutAdminRateOverride)},
	{Method: DELETE, Path: "/v1/merchant/customers/{customer_id}/rate-overrides/{meter_key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsUpdate, Limit: middleware.AdminOperationDestructive, CatalogWrite: true,
		Responses: []Reply{{200, Message{}}}, Errors: codes("invalid_param"), Handler: h(handlers.DeleteAdminRateOverride)},
	{Method: POST, Path: "/v1/merchant/catalog/offers/lookup", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Request: billing.OfferLookupRequest{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.ListOffersForEntitlements)},
	{Method: POST, Path: "/v1/merchant/catalog/products", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: service.CreateProductRequest{}, Responses: []Reply{{201, service.CatalogProduct{}}}, Errors: codes("catalog_not_found", "catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "resource_conflict"), Handler: h(handlers.AdminCreateProduct)},
	{Method: GET, Path: "/v1/merchant/catalog/products", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(text("archived"), text("catalog_id"), integer("limit"), integer("offset"), text("tier_group")), Responses: []Reply{{200, service.CatalogPage[service.CatalogProduct]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.AdminListProducts)},
	{Method: GET, Path: "/v1/merchant/catalog/products/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminGetProduct)},
	{Method: GET, Path: "/v1/merchant/catalog/products/by-key/{key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminGetProductByKey)},
	{Method: PUT, Path: "/v1/merchant/catalog/products/by-key/{key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: service.CreateProductRequest{}, Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_not_found", "catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminEnsureProduct)},
	{Method: PATCH, Path: "/v1/merchant/catalog/products/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: service.UpdateProductRequest{}, Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminUpdateProduct)},
	{Method: POST, Path: "/v1/merchant/catalog/products/{id}/activate", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminActivateProduct)},
	{Method: POST, Path: "/v1/merchant/catalog/products/{id}/deactivate", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminDeactivateProduct)},
	{Method: POST, Path: "/v1/merchant/catalog/prices", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: service.CreatePriceRequest{}, Responses: []Reply{{201, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_key_cadence_conflict", "product_not_found", "resource_conflict", "trial_unsupported_on_rail"), Handler: h(handlers.AdminCreatePrice)},
	{Method: GET, Path: "/v1/merchant/catalog/prices", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(text("archived"), text("catalog_id"), text("currency"), integer("limit"), integer("offset"), text("product_id"), text("type")), Responses: []Reply{{200, service.CatalogPage[service.CatalogPrice]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.AdminListPrices)},
	{Method: GET, Path: "/v1/merchant/catalog/prices/by-key/{key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_key_not_found"), Handler: h(handlers.AdminGetPriceByKey)},
	{Method: GET, Path: "/v1/merchant/catalog/prices/by-key/{key}/history", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, handlers.PaginatedResponse[service.PriceKeyHistoryEntry]{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_key_not_found"), Handler: h(handlers.AdminGetPriceKeyHistory)},
	{Method: GET, Path: "/v1/merchant/catalog/prices/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(text("verify")), Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminGetPrice)},
	{Method: PATCH, Path: "/v1/merchant/catalog/prices/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: service.UpdatePriceRequest{}, Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_not_found", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminUpdatePrice)},
	{Method: POST, Path: "/v1/merchant/catalog/prices/{id}/activate", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminActivatePrice)},
	{Method: POST, Path: "/v1/merchant/catalog/prices/{id}/deactivate", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminDeactivatePrice)},
	{Method: POST, Path: "/v1/merchant/catalog/prices/{id}/key", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: handlers.SetPriceKeyRequest{}, Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminSetPriceKey)},
	{Method: GET, Path: "/v1/merchant/catalog/meters", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(integer("limit"), integer("offset")), Responses: []Reply{{200, handlers.AdminUsageMeterPageResponse{}}}, Handler: h(handlers.AdminListUsageMeters)},
	{Method: GET, Path: "/v1/merchant/catalog/meters/{key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, handlers.AdminUsageMeterResponse{}}}, Errors: codes("invalid_param"), Handler: h(handlers.AdminGetUsageMeter)},
	{Method: GET, Path: "/v1/merchant/catalog/meters/{key}/overrides", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(integer("limit"), integer("offset")), Responses: []Reply{{200, handlers.PaginatedResponse[service.UsageMeterOverrideDTO]{}}}, Errors: codes("invalid_param"), Handler: h(handlers.AdminListUsageMeterOverrides)},
	{Method: PUT, Path: "/v1/merchant/catalog/meters/{key}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: handlers.AdminUsageMeterRequest{}, Responses: []Reply{{200, handlers.AdminUsageMeterResponse{}}}, Handler: h(handlers.AdminPutUsageMeter)},
	{Method: PUT, Path: "/v1/merchant/catalog/meters/{key}/rate-card", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: handlers.AdminDefaultUsageRateCardRequest{}, Responses: []Reply{{200, handlers.AdminUsageMeterResponse{}}}, Errors: codes("invalid_param"), Handler: h(handlers.AdminPutDefaultUsageRateCard)},
	{Method: DELETE, Path: "/v1/merchant/catalog/meters/{key}/rate-card", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{204, nil}}, Errors: codes("invalid_param"), Handler: h(handlers.AdminDeleteDefaultUsageRateCard)},
	{Method: GET, Path: "/v1/merchant/catalog/drift", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(text("kind"), integer("limit"), integer("offset"), text("rail"), text("resource_type")), Responses: []Reply{{200, handlers.PaginatedResponse[service.CatalogDriftEventView]{}}}, Handler: h(handlers.AdminListCatalogDrift)},
	{Method: POST, Path: "/v1/merchant/catalog/drift/refresh", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogDriftReport{}}}, Errors: codes("catalog_scope_mismatch"), Handler: h(handlers.AdminRefreshCatalogDrift)},
	{Method: GET, Path: "/v1/merchant/catalog/revision", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, billing.CatalogRevision{}}}, Handler: h(handlers.MerchantCatalogRevision)},
	{Method: POST, Path: "/v1/merchant/catalog/applications", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: catalog.Application{}, Responses: []Reply{{200, billing.CatalogApplicationReceipt{}}}, Errors: codes("catalog_application_conflict", "catalog_not_found", "catalog_owner_forbidden", "catalog_revision_conflict", "catalog_scope_mismatch", "invalid_param", "price_not_found", "price_not_sellable", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict", "trial_unsupported_on_rail"), Handler: h(handlers.MerchantApplyCatalog)},
	{Method: POST, Path: "/v1/merchant/catalog/product-archives", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, Also: billing.MerchantPaymentsRefund, CatalogWrite: true, IdempotencyKey: true,
		Request: handlers.ProductArchiveRequest{}, Responses: []Reply{{200, billing.ProductArchive{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "provider_cancel_held", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.CreateProductArchive)},
	{Method: GET, Path: "/v1/merchant/catalog/product-archives/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead, Also: billing.MerchantPaymentsRead,
		Responses: []Reply{{200, billing.ProductArchive{}}}, Errors: codes("invalid_param", "provider_cancel_held", "rebill_terms_committed", "resource_conflict", "resource_not_found"), Handler: h(handlers.GetProductArchive)},
	{Method: GET, Path: "/v1/merchant/catalogs", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(integer("limit"), integer("offset")), Responses: []Reply{{200, Untyped{}}}, Errors: codes("invalid_param"), Handler: h(handlers.ListCatalogs)},
	{Method: POST, Path: "/v1/merchant/catalogs", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, CatalogWrite: true,
		Request: Untyped{}, Responses: []Reply{{200, billing.Catalog{}}}, Errors: codes("invalid_param"), Handler: h(handlers.EnsureCatalogForOwner)},
	{Method: GET, Path: "/v1/merchant/catalogs/by-owner", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Query: params(text("owner_subject")), Responses: []Reply{{200, billing.Catalog{}}}, Errors: codes("invalid_param", "resource_not_found"), Handler: h(handlers.GetCatalogForOwner)},
	{Method: GET, Path: "/v1/merchant/catalogs/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead,
		Responses: []Reply{{200, billing.Catalog{}}}, Errors: codes("invalid_param", "resource_not_found"), Handler: h(handlers.GetCatalog)},
	{Method: GET, Path: "/v1/catalog", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Responses: []Reply{{200, billing.Catalog{}}}, Errors: codes("resource_access_denied"), Handler: h(handlers.OwnCatalog)},
	{Method: PUT, Path: "/v1/catalog", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Responses: []Reply{{200, billing.Catalog{}}}, Errors: codes("resource_access_denied"), Handler: h(handlers.OwnCatalog)},
	{Method: GET, Path: "/v1/catalog/products", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Query: params(text("archived"), text("catalog_id"), integer("limit"), integer("offset"), text("tier_group")), Responses: []Reply{{200, service.CatalogPage[service.CatalogProduct]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.AdminListProducts)},
	{Method: POST, Path: "/v1/catalog/offers/lookup", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Request: billing.OfferLookupRequest{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.ListOffersForEntitlements)},
	{Method: POST, Path: "/v1/catalog/products", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: service.CreateProductRequest{}, Responses: []Reply{{201, service.CatalogProduct{}}}, Errors: codes("catalog_not_found", "catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "resource_conflict"), Handler: h(handlers.AdminCreateProduct)},
	{Method: GET, Path: "/v1/catalog/products/by-key/{key}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminGetProductByKey)},
	{Method: PUT, Path: "/v1/catalog/products/by-key/{key}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: service.CreateProductRequest{}, Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_not_found", "catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminEnsureProduct)},
	{Method: GET, Path: "/v1/catalog/products/{id}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminGetProduct)},
	{Method: PATCH, Path: "/v1/catalog/products/{id}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: service.UpdateProductRequest{}, Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminUpdateProduct)},
	{Method: POST, Path: "/v1/catalog/products/{id}/activate", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminActivateProduct)},
	{Method: POST, Path: "/v1/catalog/products/{id}/deactivate", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogProduct{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "product_not_found", "product_tier_group_conflict", "product_tier_group_in_use", "resource_conflict"), Handler: h(handlers.AdminDeactivateProduct)},
	{Method: GET, Path: "/v1/catalog/prices", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Query: params(text("archived"), text("catalog_id"), text("currency"), integer("limit"), integer("offset"), text("product_id"), text("type")), Responses: []Reply{{200, service.CatalogPage[service.CatalogPrice]{}}}, Errors: codes("catalog_not_found", "catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.AdminListPrices)},
	{Method: POST, Path: "/v1/catalog/prices", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: service.CreatePriceRequest{}, Responses: []Reply{{201, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_key_cadence_conflict", "product_not_found", "resource_conflict", "trial_unsupported_on_rail"), Handler: h(handlers.AdminCreatePrice)},
	{Method: GET, Path: "/v1/catalog/prices/by-key/{key}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_key_not_found"), Handler: h(handlers.AdminGetPriceByKey)},
	{Method: GET, Path: "/v1/catalog/prices/by-key/{key}/history", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Responses: []Reply{{200, handlers.PaginatedResponse[service.PriceKeyHistoryEntry]{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_key_not_found"), Handler: h(handlers.AdminGetPriceKeyHistory)},
	{Method: GET, Path: "/v1/catalog/prices/{id}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnRead,
		Query: params(text("verify")), Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminGetPrice)},
	{Method: PATCH, Path: "/v1/catalog/prices/{id}", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: service.UpdatePriceRequest{}, Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_owner_forbidden", "catalog_scope_mismatch", "invalid_param", "price_not_found", "product_not_found", "resource_conflict"), Handler: h(handlers.AdminUpdatePrice)},
	{Method: POST, Path: "/v1/catalog/prices/{id}/activate", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminActivatePrice)},
	{Method: POST, Path: "/v1/catalog/prices/{id}/deactivate", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminDeactivatePrice)},
	{Method: POST, Path: "/v1/catalog/prices/{id}/key", Group: CatalogOwned, Auth: AuthMerchant, Perm: billing.MerchantCatalogOwnUpdate, CatalogWrite: true,
		Request: handlers.SetPriceKeyRequest{}, Responses: []Reply{{200, service.CatalogPrice{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "price_not_found", "resource_conflict"), Handler: h(handlers.AdminSetPriceKey)},

	// #779 catalog copilot: read-only Q&A over the catalog, mounted only when
	// the copilot is configured. It never changes a catalog row, so it is not
	// a catalog write; confirm records that a draft was applied, which only
	// a caller who could apply it may log.
	{Method: POST, Path: "/v1/merchant/catalog/ask", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogRead, When: FeatureCatalogCopilot,
		Request: Untyped{}, Responses: []Reply{{200, copilot.AskResult{}}}, Errors: codes("invalid_param", "rate_limit_exceeded", "service_unavailable"), Handler: h(handlers.CatalogCopilotAsk)},
	{Method: POST, Path: "/v1/merchant/catalog/copilot/confirm", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCatalogUpdate, When: FeatureCatalogCopilot,
		Request: Untyped{}, Responses: []Reply{{200, Message{}}}, Errors: codes("invalid_param"), Handler: h(handlers.CatalogCopilotConfirmDraft)},
}
