package routes

import (
	"net/http"

	"github.com/open-rails/openrails/billing"
	"github.com/open-rails/openrails/internal/http/handlers"
	"github.com/open-rails/openrails/internal/merchants"
	"github.com/open-rails/openrails/internal/modules/checkout"
	"github.com/open-rails/openrails/internal/service"
)

// checkoutRoutes is buying: the public discovery a checkout page needs, the
// engine checkout (created by a signed-in user, a customer or the merchant's
// own server), the hosted checkout session a browser reads and pays by its
// id, and the session doors for card setup and Solana changes.
var checkoutRoutes = []Route{
	{Method: GET, Path: "/v1/checkout-config", Group: Checkout, Auth: AuthPublic,
		Responses: []Reply{{200, merchants.PublicCheckoutConfig{}}}, Errors: codes("resource_not_found", "service_unavailable"), Handler: h(handlers.GetCheckoutConfig)},
	{Method: GET, Path: "/v1/solana/config", Group: Checkout, Auth: AuthPublic, When: FeatureSolana,
		Responses: []Reply{{200, handlers.SolanaRuntimeConfigResponse{}}}, Handler: h(handlers.GetSolanaConfig)},
	{Method: GET, Path: "/v1/solana/tokens", Group: Checkout, Auth: AuthPublic, When: FeatureSolana,
		Query: queryOf(handlers.SupportedTokensQuery{}), Responses: []Reply{{200, handlers.SupportedTokensResponse{}}}, Errors: codes("catalog_scope_mismatch", "credential_custody_transition_required", "resource_conflict"), Handler: h(handlers.GetSupportedTokens)},
	{Method: POST, Path: "/v1/checkout", Group: Checkout, Auth: AuthUser, IdempotencyKey: true,
		Request: handlers.CheckoutSessionCreateRequest{}, Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "card_requires_https", "catalog_scope_mismatch", "credential_custody_transition_required", "custodian_capture_unavailable", "customer_action_required", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.CreateCheckoutSession)},
	{Method: GET, Path: "/v1/checkout/{id}", Group: Checkout, Auth: AuthUser,
		Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.GetCheckoutSession)},
	{Method: POST, Path: "/v1/checkout/{id}/confirm", Group: Checkout, Auth: AuthUser,
		Request: handlers.CheckoutSessionConfirmRequest{}, Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}, {202, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ConfirmCheckoutSession)},
	{Method: GET, Path: "/v1/checkout-sessions/{id}", Group: Checkout, Auth: AuthSessionID, Throttle: ThrottleSessionRead,
		Responses: []Reply{{200, billing.HostedCheckoutSession{}}}, Errors: codes("card_attempts_blocked", "card_declined", "card_not_saved", "checkout_session_not_found", "checkout_session_unavailable", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.GetHostedCheckoutSession)},
	{Method: POST, Path: "/v1/checkout-sessions/{id}/pay", Group: Checkout, Auth: AuthSessionID, Throttle: ThrottleSessionPay,
		Request: billing.HostedCheckoutPayRequest{}, Responses: []Reply{{200, billing.HostedCheckoutPayResult{}}}, Errors: codes("card_attempts_blocked", "card_declined", "card_not_saved", "card_requires_https", "catalog_scope_mismatch", "checkout_offer_unavailable", "checkout_payment_in_progress", "checkout_request_invalid", "checkout_session_expired", "checkout_session_not_found", "checkout_session_unavailable", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.PayHostedCheckoutSession)},
	{Method: GET, Path: "/v1/checkout/{id}/solana-pay", Group: Checkout, Auth: AuthSessionID, When: FeatureSolana,
		Responses: []Reply{{200, handlers.SolanaPayGetResponse{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "resource_conflict", "resource_not_found"), Handler: h(handlers.GetSolanaPay)},
	{Method: POST, Path: "/v1/checkout/{id}/solana-pay", Group: Checkout, Auth: AuthSessionID, When: FeatureSolana,
		Request: handlers.SolanaPayPostRequest{}, Responses: []Reply{{200, handlers.SolanaPayPostResponse{}}}, Errors: codes("invalid_param", "resource_conflict", "resource_not_found"), Handler: h(handlers.PostSolanaPay)},
	{Method: POST, Path: "/v1/merchant/checkout-sessions", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate, IdempotencyKey: true,
		Request: billing.CreateCheckoutSessionRequest{}, Responses: []Reply{{200, service.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "card_requires_https", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceCreateCheckoutSession)},
	{Method: POST, Path: "/v1/merchant/checkout-sessions/lookup", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate, IdempotencyKey: true,
		Request: billing.CreateCheckoutSessionRequest{}, Responses: []Reply{{200, service.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceLookupCheckoutSession)},
	{Method: POST, Path: "/v1/merchant/hosted-checkout-sessions", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate,
		Request: billing.CreateHostedCheckoutSessionRequest{}, Responses: []Reply{{201, billing.HostedCheckoutSessionLink{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "catalog_scope_mismatch", "checkout_offer_unavailable", "checkout_session_unavailable", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceCreateHostedCheckoutSession)},
	{Method: POST, Path: "/v1/merchant/payment-method-sessions", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate, IdempotencyKey: true,
		Request: billing.CreatePaymentMethodSessionRequest{}, Responses: []Reply{{200, billing.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceCreatePaymentMethodSession)},
	{Method: POST, Path: "/v1/merchant/solana-cancel-sessions", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate, IdempotencyKey: true,
		Request: billing.CreateSolanaCancelSessionRequest{}, Responses: []Reply{{200, billing.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceCreateSolanaCancelSession)},
	{Method: POST, Path: "/v1/merchant/solana-tier-change-sessions", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate, IdempotencyKey: true,
		Request: billing.CreateSolanaTierChangeSessionRequest{}, Responses: []Reply{{200, billing.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceCreateSolanaTierChangeSession)},
	{Method: GET, Path: "/v1/merchant/checkout-sessions/by-key", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead, IdempotencyKey: true,
		Query: params(text("customer_id"), text("entitlement")), Responses: []Reply{{200, service.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceGetCheckoutSessionByKey)},
	{Method: GET, Path: "/v1/merchant/checkout-sessions/{id}", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead,
		Query: params(text("customer_id")), Responses: []Reply{{200, service.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceGetCheckoutSession)},
	{Method: POST, Path: "/v1/merchant/checkout-sessions/{id}/confirm", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCheckoutCreate,
		Request: billing.ConfirmCheckoutSessionRequest{}, Responses: []Reply{{200, service.CheckoutSession{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceConfirmCheckoutSession)},
	{Method: GET, Path: "/v1/merchant/checkout-options", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead,
		Query: params(text("price_id"), text("price_key")), Responses: []Reply{{200, []service.CheckoutRailOption{}}}, Errors: codes("card_attempts_blocked", "card_declined", "card_not_saved", "catalog_scope_mismatch", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceListCheckoutRailOptions)},
	{Method: GET, Path: "/v1/merchant/checkout-config", Group: Merchant, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead,
		Responses: []Reply{{200, merchants.PublicCheckoutConfig{}}}, Errors: codes("resource_not_found", "service_unavailable"), Handler: h(handlers.ServiceGetCheckoutConfig)},
	{Method: POST, Path: "/v1/me/checkout", Group: Customer, Auth: AuthCustomer, IdempotencyKey: true,
		Request: handlers.CheckoutSessionCreateRequest{}, Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "card_requires_https", "catalog_scope_mismatch", "credential_custody_transition_required", "custodian_capture_unavailable", "customer_action_required", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.CreateCheckoutSession)},
	{Method: POST, Path: "/v1/me/checkout/sessions", Group: Customer, Auth: AuthCustomer, When: FeatureHostedCheckout,
		Request: handlers.HostedCheckoutMintRequest{}, Responses: []Reply{{201, billing.HostedCheckoutSessionLink{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "catalog_scope_mismatch", "checkout_offer_unavailable", "checkout_session_unavailable", "custodian_capture_unavailable", "customer_action_required", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.CreateHostedCheckoutSession)},
	{Method: GET, Path: "/v1/me/checkout/{id}", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "credential_custody_transition_required", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.GetCheckoutSession)},
	{Method: POST, Path: "/v1/me/checkout/{id}/confirm", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Request: handlers.CheckoutSessionConfirmRequest{}, Responses: []Reply{{200, checkout.CheckoutSessionResponse{}}, {202, checkout.CheckoutSessionResponse{}}}, Errors: codes("authentication_required", "card_attempts_blocked", "card_declined", "card_not_saved", "custodian_capture_unavailable", "idempotency_key_reused", "insufficient_funds", "invalid_param", "payment_method_required", "payment_method_stale", "payment_provider_rejected", "resource_access_denied", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.ConfirmCheckoutSession)},

	// Captcha discovery: whether this caller must solve one, and the script
	// that does. The assembly builds both from its captcha configuration.
	{Method: GET, Path: "/v1/captcha/status", Group: Checkout, Auth: AuthPublic, NoConn: true,
		Responses: []Reply{{200, Untyped{}}}, Bind: external(func(x *External) http.Handler { return x.CaptchaStatus })},
	{Method: GET, Path: "/v1/captcha/client.js", Group: Checkout, Auth: AuthPublic, NoConn: true,
		Responses: []Reply{{200, Stream{"application/javascript"}}}, Bind: external(func(x *External) http.Handler { return x.CaptchaScript })},
}
