package routes

import (
	"github.com/open-rails/openrails/billing"
	"github.com/open-rails/openrails/internal/api"
	"github.com/open-rails/openrails/internal/http/handlers"
	"github.com/open-rails/openrails/internal/http/middleware"
	"github.com/open-rails/openrails/internal/modules/checkout"
	"github.com/open-rails/openrails/internal/modules/subscriptions"
	"github.com/open-rails/openrails/internal/query"
	"github.com/open-rails/openrails/internal/service"
)

// subscriptionsRoutes is recurring agreements: reading, cancelling, resuming
// and changing a subscription as the customer or as merchant staff, and the
// merchant's bulk moves (reprices, plan migrations, PSP cutovers, engine
// takeovers).
var subscriptionsRoutes = []Route{
	{Method: GET, Path: "/v1/merchant/customers/{customer_id}/effective-tier", Group: MerchantAPI, Auth: AuthMerchant, Perm: billing.MerchantCustomerSettingsRead,
		Query: params(text("group")), Responses: []Reply{{200, service.EffectiveTier{}}}, Errors: codes("authentication_required", "invalid_param"), Handler: h(handlers.ServiceResolveEffectiveTier)},
	{Method: GET, Path: "/v1/merchant/subscriptions", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(queryOf(query.QueryOptions[subscriptions.GetSubscriptionsFilters]{}), queryOf(subscriptions.GetSubscriptionsFilters{})), Responses: []Reply{{200, api.List[billing.Subscription]{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param"), Handler: h(handlers.GetAdminSubscriptions)},
	{Method: GET, Path: "/v1/merchant/subscriptions/{id}", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Responses: []Reply{{200, billing.Subscription{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "subscription_not_found"), Handler: h(handlers.GetAdminSubscription)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/cancel", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate, Limit: middleware.AdminOperationDestructive,
		Request: handlers.AdminCancelSubscriptionRequest{}, Responses: []Reply{{200, Message{}}}, Errors: codes("cancel_unsupported_on_rail", "invalid_param", "provider_cancel_held", "resource_conflict", "solana_cancel_needs_wallet_signature", "subscription_not_active", "subscription_not_found"), Handler: h(handlers.AdminCancelSubscription)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/resume", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{202, Untyped{}}}, Errors: codes("invalid_param", "resource_not_found"), Handler: h(handlers.AdminResumeSubscription)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/change-tier", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate, Limit: middleware.AdminOperationOffChannel, IdempotencyKey: true,
		Request: handlers.ChangeTierRequest{}, Responses: []Reply{{200, checkout.TierChangeResponse{}}, {202, checkout.TierChangeResponse{}}}, Errors: codes("card_declined", "catalog_scope_mismatch", "invalid_param", "payment_method_stale", "payment_provider_rejected", "rebill_terms_committed", "reprice_already_scheduled", "reprice_cross_currency", "resource_conflict", "resource_not_found", "tier_change_already_scheduled", "tier_change_in_flight"), Handler: h(handlers.AdminChangeTier)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/change-tier/preview", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: handlers.ChangeTierRequest{}, Responses: []Reply{{200, checkout.TierChangePreviewResponse{}}}, Errors: codes("card_declined", "catalog_scope_mismatch", "invalid_param", "payment_method_stale", "payment_provider_rejected", "reprice_cross_currency", "resource_conflict", "resource_not_found", "tier_change_already_scheduled", "tier_change_in_flight"), Handler: h(handlers.AdminChangeTierPreview)},
	{Method: PUT, Path: "/v1/merchant/subscriptions/{id}/payment-method", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: handlers.UpdateSubscriptionPaymentMethodBody{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("invalid_param", "payment_method_not_psp_vaulted", "payment_method_psp_mismatch", "payment_method_same_vault", "rebill_terms_committed", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.AdminUpdateSubscriptionPaymentMethod)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/provider-cutover", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Query: params(text("idempotency_key")), Request: billing.ProviderCutoverRequest{}, Responses: []Reply{{200, billing.ProviderCutover{}}, {202, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.ProviderCutover)},
	{Method: GET, Path: "/v1/merchant/subscriptions/{id}/provider-cutover", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(text("idempotency_key")), Responses: []Reply{{200, billing.ProviderCutover{}}, {202, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.ProviderCutover)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/provider-cutover/preview", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(text("idempotency_key")), Request: billing.ProviderCutoverRequest{}, Responses: []Reply{{200, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.PreviewProviderCutover)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/engine-takeover/preview", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Responses: []Reply{{200, billing.EngineTakeover{}}}, Errors: codes("catalog_scope_mismatch", "rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.PreviewEngineTakeover)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/engine-takeover", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{200, billing.EngineTakeover{}}, {202, billing.EngineTakeover{}}}, Errors: codes("catalog_scope_mismatch", "rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.EngineTakeover)},
	{Method: GET, Path: "/v1/merchant/subscriptions/{id}/engine-takeover", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Responses: []Reply{{200, billing.EngineTakeover{}}}, Errors: codes("catalog_scope_mismatch", "rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.GetEngineTakeover)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/engine-takeover/abandon", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{200, billing.EngineTakeover{}}, {202, billing.EngineTakeover{}}}, Errors: codes("catalog_scope_mismatch", "rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.AbandonEngineTakeover)},
	{Method: POST, Path: "/v1/merchant/engine-takeovers", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: billing.EngineTakeoverBatchRequest{}, Responses: []Reply{{200, billing.EngineTakeoverBatchResult{}}}, Errors: codes("catalog_scope_mismatch", "rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.EngineTakeoverBatch)},
	{Method: POST, Path: "/v1/merchant/provider-refresh", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{202, billing.ProviderRefresh{}}}, Errors: codes("service_unavailable"), Handler: h(handlers.RefreshProviders)},
	{Method: POST, Path: "/v1/merchant/subscriptions/{id}/reprice", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: handlers.CreateSubscriptionRepriceRequest{}, Responses: []Reply{{201, subscriptions.SubscriptionRepriceView{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "rebill_terms_committed", "reprice_already_scheduled", "reprice_cross_currency", "reprice_cross_product", "reprice_inactive_price", "reprice_not_scheduled", "reprice_notice_window_violation", "reprice_target_price_not_found", "subscription_not_found"), Handler: h(handlers.CreateSubscriptionReprice)},
	{Method: POST, Path: "/v1/merchant/catalog/reprice-all-prior-versions", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: handlers.RepriceAllPriorVersionsRequest{}, Responses: []Reply{{201, subscriptions.RepriceBatchResult{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "rebill_terms_committed", "reprice_already_scheduled", "reprice_cross_currency", "reprice_cross_product", "reprice_inactive_price", "reprice_not_scheduled", "reprice_notice_window_violation", "reprice_price_key_not_found"), Handler: h(handlers.RepriceAllPriorVersions)},
	{Method: GET, Path: "/v1/merchant/catalog/reprice-all-prior-versions/preview", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(text("price_key")), Responses: []Reply{{200, subscriptions.RepricePreviewResult{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "reprice_price_key_not_found"), Handler: h(handlers.PreviewRepriceAllPriorVersions)},
	{Method: POST, Path: "/v1/merchant/plan-migrations", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Request: billing.PlanMigrationRequest{}, Responses: []Reply{{201, subscriptions.PlanMigrationResult{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "rebill_terms_committed", "reprice_already_scheduled", "reprice_cross_currency", "reprice_inactive_price", "reprice_not_scheduled", "reprice_notice_window_violation", "resource_not_found"), Handler: h(handlers.CreatePlanMigration)},
	{Method: POST, Path: "/v1/merchant/plan-migrations/preview", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Request: billing.PlanMigrationRequest{}, Responses: []Reply{{200, subscriptions.PlanMigrationResult{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "reprice_already_scheduled", "reprice_cross_currency", "reprice_inactive_price", "reprice_notice_window_violation", "resource_not_found"), Handler: h(handlers.PreviewPlanMigration)},
	{Method: GET, Path: "/v1/merchant/plan-migrations/{id}", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(integer("limit"), integer("offset")), Responses: []Reply{{200, Untyped{}}}, Errors: codes("invalid_param"), Handler: h(handlers.GetPlanMigration)},
	{Method: POST, Path: "/v1/merchant/plan-migrations/{id}/cancel", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{200, subscriptions.PlanMigrationCancelResult{}}}, Errors: codes("invalid_param", "rebill_terms_committed", "reprice_not_scheduled"), Handler: h(handlers.CancelPlanMigration)},
	{Method: GET, Path: "/v1/merchant/reprices", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(integer("limit"), integer("offset"), text("reprice_batch_id"), text("status"), text("subscription_id")), Responses: []Reply{{200, handlers.PaginatedResponse[subscriptions.SubscriptionRepriceView]{}}}, Errors: codes("invalid_param"), Handler: h(handlers.ListSubscriptionReprices)},
	{Method: GET, Path: "/v1/merchant/reprices/batches", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Query: params(integer("limit"), integer("offset"), text("price_key")), Responses: []Reply{{200, handlers.PaginatedResponse[subscriptions.RepriceBatchView]{}}}, Errors: codes("invalid_param"), Handler: h(handlers.ListRepriceBatchesByKey)},
	{Method: GET, Path: "/v1/merchant/reprices/{id}", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsRead,
		Responses: []Reply{{200, subscriptions.SubscriptionRepriceView{}}}, Errors: codes("invalid_param", "reprice_not_found"), Handler: h(handlers.GetSubscriptionReprice)},
	{Method: POST, Path: "/v1/merchant/reprices/{id}/cancel", Group: MerchantAdmin, Auth: AuthMerchant, Perm: billing.MerchantSubscriptionsUpdate,
		Responses: []Reply{{200, Message{}}}, Errors: codes("invalid_param", "rebill_terms_committed", "reprice_not_scheduled"), Handler: h(handlers.CancelSubscriptionReprice)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/cancel", Group: Customer, Auth: AuthCustomer, Scope: ScopeSubscriptionManagement,
		Request: handlers.CancelSubscriptionRequest{}, Responses: []Reply{{202, Untyped{}}}, Errors: codes("authentication_required", "invalid_param", "provider_cancel_held", "resource_not_found", "solana_cancel_needs_wallet_signature"), Handler: h(handlers.CancelSubscription)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/resume", Group: Customer, Auth: AuthCustomer, Scope: ScopeSubscriptionManagement,
		Responses: []Reply{{202, Untyped{}}}, Errors: codes("authentication_required", "invalid_param", "resource_not_found"), Handler: h(handlers.ResumeSubscription)},
	{Method: PUT, Path: "/v1/me/subscriptions/{id}/payment-method", Group: Customer, Auth: AuthCustomer, Scope: ScopeSubscriptionManagement,
		Request: handlers.UpdateSubscriptionPaymentMethodBody{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("authentication_required", "invalid_param", "payment_method_not_psp_vaulted", "payment_method_psp_mismatch", "payment_method_same_vault", "rebill_terms_committed", "resource_conflict", "resource_not_found", "service_unavailable"), Handler: h(handlers.UpdateSubscriptionPaymentMethod)},
	{Method: GET, Path: "/v1/me/tier", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Query: params(text("at"), text("group")), Responses: []Reply{{200, handlers.EffectiveTierResponse{}}}, Errors: codes("authentication_required", "invalid_param"), Handler: h(handlers.GetMyTier)},
	{Method: GET, Path: "/v1/me/subscriptions", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Query: params(integer("limit"), integer("offset"), text("status")), Responses: []Reply{{200, PathPage[billing.Subscription]{}}}, Errors: codes("authentication_required", "catalog_scope_mismatch"), Handler: h(handlers.GetMySubscriptions)},
	{Method: GET, Path: "/v1/me/subscriptions/{id}", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Responses: []Reply{{200, billing.Subscription{}}}, Errors: codes("authentication_required", "catalog_scope_mismatch", "invalid_param", "resource_not_found", "subscription_not_found"), Handler: h(handlers.GetSubscription)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/retry-now", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement,
		Request: billing.RetrySubscriptionNowRequest{}, Responses: []Reply{{200, billing.SubscriptionRetryNowResult{}}, {202, billing.SubscriptionRetryNowResult{}}}, Errors: codes("authentication_required", "card_declined", "catalog_scope_mismatch", "customer_action_required", "customer_payment_unsupported", "invalid_param", "invalid_payment_method", "payment_idempotency_conflict", "payment_in_progress", "payment_not_retryable", "payment_provider_rejected", "rebill_terms_committed", "resource_conflict", "resource_not_found", "subscription_not_found"), Handler: h(handlers.RetryMySubscriptionNow)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/change-tier", Group: Customer, Auth: AuthCustomer, IdempotencyKey: true,
		Request: handlers.ChangeTierRequest{}, Responses: []Reply{{200, checkout.TierChangeResponse{}}, {202, checkout.TierChangeResponse{}}}, Errors: codes("authentication_required", "card_declined", "catalog_scope_mismatch", "customer_action_required", "invalid_param", "payment_method_stale", "payment_provider_rejected", "rebill_terms_committed", "reprice_already_scheduled", "reprice_cross_currency", "resource_conflict", "resource_not_found", "tier_change_in_flight"), Handler: h(handlers.ChangeTier)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/change-tier/preview", Group: Customer, Auth: AuthCustomer,
		Request: handlers.ChangeTierRequest{}, Responses: []Reply{{200, checkout.TierChangePreviewResponse{}}}, Errors: codes("authentication_required", "card_declined", "catalog_scope_mismatch", "invalid_param", "payment_method_stale", "payment_provider_rejected", "reprice_cross_currency", "resource_conflict", "resource_not_found", "tier_change_in_flight"), Handler: h(handlers.ChangeTierPreview)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/provider-cutover", Group: Customer, Auth: AuthCustomer,
		Query: params(text("idempotency_key")), Request: billing.ProviderCutoverRequest{}, Responses: []Reply{{200, billing.ProviderCutover{}}, {202, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.MyProviderCutover)},
	{Method: GET, Path: "/v1/me/subscriptions/{id}/provider-cutover", Group: Customer, Auth: AuthCustomer,
		Query: params(text("idempotency_key")), Responses: []Reply{{200, billing.ProviderCutover{}}, {202, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.MyProviderCutover)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/provider-cutover/preview", Group: Customer, Auth: AuthCustomer,
		Query: params(text("idempotency_key")), Request: billing.ProviderCutoverRequest{}, Responses: []Reply{{200, billing.ProviderCutover{}}}, Errors: codes("rate_limit_exceeded", "rebill_terms_committed", "resource_conflict"), Handler: h(handlers.PreviewMyProviderCutover)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/solana-cancel-tx", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement, When: FeatureSolanaSigning,
		Responses: []Reply{{200, Untyped{}}}, Errors: codes("authentication_required", "invalid_param", "resource_not_found", "service_unavailable"), Handler: h(handlers.PrepareSolanaCancelTx)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/solana-cancel", Group: Customer, Auth: AuthCustomer, Scope: ScopeBillingManagement, When: FeatureSolanaSigning,
		Request: handlers.ConfirmSolanaCancelRequest{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("authentication_required", "invalid_param", "resource_not_found", "service_unavailable"), Handler: h(handlers.ConfirmSolanaCancel)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/solana-tier-change", Group: Customer, Auth: AuthCustomer, When: FeatureSolanaSigning,
		Request: handlers.SolanaTierChangeRequest{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "service_unavailable"), Handler: h(handlers.PrepareSolanaTierChange)},
	{Method: POST, Path: "/v1/me/subscriptions/{id}/solana-tier-change/confirm", Group: Customer, Auth: AuthCustomer, When: FeatureSolanaSigning,
		Request: handlers.SolanaTierChangeConfirmRequest{}, Responses: []Reply{{200, Untyped{}}}, Errors: codes("catalog_scope_mismatch", "invalid_param", "service_unavailable"), Handler: h(handlers.ConfirmSolanaTierChange)},
}
