// Framework-free client for the OpenRails customer surface (`/billing/v1/me/*`)
// and public catalog.
export {
  CANCEL_FEEDBACK_MAX,
  CANCEL_FEEDBACK_MIN,
  createBillingClient,
  isWalletRejection,
  RETRY_BUDGET_MS,
  WalletRejectedError,
  type BillingClient,
  type BillingClientOptions,
  type ListOptions,
  type SendSolanaTransaction,
  type SolanaCancelStage,
} from "./client"
export {
  BillingError,
  isBillingError,
  isServerError,
  readBillingError,
  toBillingError,
  type BillingErrorBody,
} from "./errors"
export type {
  BillingStatus,
  CardSetup,
  CardSummary,
  Currency,
  CurrencyScales,
  Invoice,
  NewCard,
  Page,
  Payment,
  PaymentAuthentication,
  PaymentMethod,
  PaymentOperation,
  PaymentRecovery,
  Price,
  Product,
  SolanaConfig,
  SolanaTierChange,
  SolanaTierChangeTx,
  SolanaToken,
  Subscription,
  SubscriptionPrice,
  SubscriptionProduct,
  SubscriptionStatus,
  TierChange,
  TierChangePreview,
} from "./types"
export { amountToDecimal, formatAmount, type Amount } from "../lib/money"
