// Framework-free client for the OpenRails customer surface (`/billing/v1/me/*`)
// and public catalog.
export {
  CANCEL_REASON_MAX,
  CANCEL_REASON_MIN,
  createBillingClient,
  isWalletAction,
  isWalletRejection,
  RETRY_BUDGET_MS,
  signWalletAction,
  WalletRejectedError,
  type BillingClient,
  type BillingClientOptions,
  type ListOptions,
  type SendSolanaTransaction,
} from "./client"
export {
  BillingError,
  isBillingError,
  isServerError,
  readBillingError,
  toBillingError,
  type BillingErrorBody,
} from "./errors"
export type {
  CardSetup,
  CardSummary,
  Currency,
  CurrencyScales,
  CheckoutConfig,
  CheckoutSessionLink,
  Invoice,
  ListPage,
  NewCard,
  NextAction,
  Page,
  Payment,
  PaymentAuthentication,
  PaymentMethod,
  PaymentOperation,
  PaymentRecovery,
  Price,
  Product,
  SolanaToken,
  Subscription,
  SubscriptionProduct,
  SubscriptionStatus,
  TierChange,
  TierChangePreview,
} from "./types"
export { amountToDecimal, formatAmount, type Amount } from "../lib/money"
