// Command contract writes the in-repo OpenRails customer route catalog and the
// hosted-checkout document shape into src/client/generated.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/open-rails/openrails"

	"github.com/open-rails/openrails/sdk/billing-ui/e2e/server/harness"
)

const (
	scopeSelfService = "self_service"
	scopeManagement  = "billing_management"
)

type route struct {
	Method string   `json:"method"`
	Path   string   `json:"path"`
	Scopes []string `json:"scopes"`
}

type field struct {
	Name     string  `json:"name"`
	Type     string  `json:"type"`
	Optional bool    `json:"optional,omitempty"`
	Fields   []field `json:"fields,omitempty"`
}

type contract struct {
	Routes                []route `json:"routes"`
	HostedCheckoutSession []field `json:"hosted_checkout_session"`
}

func main() {
	out := flag.String("out", "../../src/client/generated", "output directory")
	dsn := flag.String("dsn", os.Getenv("DATABASE_URL"), "migratable Postgres DSN")
	flag.Parse()
	if err := run(*out, *dsn); err != nil {
		log.Fatal(err)
	}
}

func run(out, dsn string) error {
	ctx := context.Background()
	pool, err := harness.Open(ctx, dsn)
	if err != nil {
		return err
	}
	defer pool.Close()
	rt, err := harness.New(ctx, "http://localhost", dsn, pool, false)
	if err != nil {
		return err
	}
	defer rt.Close()
	mounted, err := rt.BillingRoutes()
	if err != nil {
		return err
	}

	byKey := map[string]*route{}
	for _, r := range mounted {
		if r.Method == http.MethodOptions {
			continue
		}
		path, scope := r.Path, scopeSelfService
		switch {
		case strings.HasPrefix(path, harness.ManagePrefix+"/"):
			path, scope = "/v1/me"+strings.TrimPrefix(path, harness.ManagePrefix), scopeManagement
		case !strings.HasPrefix(path, "/v1/me/"):
			continue
		}
		path = "/billing" + path
		key := r.Method + " " + path
		if byKey[key] == nil {
			byKey[key] = &route{Method: r.Method, Path: path}
		}
		byKey[key].Scopes = append(byKey[key].Scopes, scope)
	}
	c := contract{HostedCheckoutSession: shape(reflect.TypeFor[openrails.HostedCheckoutSession]())}
	for _, r := range byKey {
		sort.Strings(r.Scopes)
		c.Routes = append(c.Routes, *r)
	}
	sort.Slice(c.Routes, func(i, j int) bool {
		if c.Routes[i].Path != c.Routes[j].Path {
			return c.Routes[i].Path < c.Routes[j].Path
		}
		return c.Routes[i].Method < c.Routes[j].Method
	})

	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	var js bytes.Buffer
	enc := json.NewEncoder(&js)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(c); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(out, "openrails-contract.json"), js.Bytes(), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(out, "openrails-routes.ts"), routesTS(c), 0o644)
}

var timeType = reflect.TypeFor[time.Time]()

// shape describes t's JSON encoding: names, wire types and omitempty.
func shape(t reflect.Type) []field {
	var fields []field
	for i := range t.NumField() {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if !f.IsExported() || tag == "-" {
			continue
		}
		parts := strings.Split(tag, ",")
		name, opts := parts[0], parts[1:]
		if name == "" {
			name = f.Name
		}
		ft := f.Type
		optional := ft.Kind() == reflect.Pointer
		for _, o := range opts {
			optional = optional || o == "omitempty" || o == "omitzero"
		}
		for ft.Kind() == reflect.Pointer {
			ft = ft.Elem()
		}
		out := field{Name: name, Optional: optional, Type: wireType(ft, opts)}
		elem := ft
		if ft.Kind() == reflect.Slice {
			elem = ft.Elem()
		}
		if elem.Kind() == reflect.Struct && elem != timeType {
			out.Fields = shape(elem)
		}
		fields = append(fields, out)
	}
	return fields
}

func wireType(t reflect.Type, opts []string) string {
	for _, o := range opts {
		if o == "string" {
			return "string"
		}
	}
	if t == timeType {
		return "string"
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice:
		return "array"
	case reflect.Map, reflect.Struct:
		return "object"
	}
	return "unknown"
}

func routesTS(c contract) []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by `pnpm contract` from the in-repo OpenRails. Do not edit.\n\n")
	b.WriteString("export type OpenRailsCustomerRoute =\n")
	for _, r := range c.Routes {
		fmt.Fprintf(&b, "  | %q\n", r.Method+" "+r.Path)
	}
	// The registry is fixed per OpenRails release; amounts on /me carry no scale.
	b.WriteString("\n// Currency code to native-unit decimals (openrails.Currencies()).\n")
	b.WriteString("export const OPENRAILS_CURRENCY_SCALES: Readonly<Record<string, number>> = {\n")
	for _, cur := range openrails.Currencies() {
		fmt.Fprintf(&b, "  %s: %d,\n", cur.Code, cur.Decimals)
	}
	b.WriteString("}\n")
	return b.Bytes()
}
