SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

-- Validate in a separate transaction from0021 so its access-exclusive table
-- locks are released before existing financial and snapshot rows are scanned.
ALTER TABLE openrails.metered_rating_watermarks VALIDATE CONSTRAINT metered_rating_watermarks_currency_shape;
ALTER TABLE openrails.catalog_credit_purchase_prices VALIDATE CONSTRAINT catalog_credit_purchase_prices_currency_shape;
ALTER TABLE openrails.host_lifecycle_events VALIDATE CONSTRAINT host_lifecycle_events_currency_shape;
ALTER TABLE openrails.invoices VALIDATE CONSTRAINT invoices_currency_shape;
ALTER TABLE openrails.ledger_accounts VALIDATE CONSTRAINT ledger_accounts_currency_shape;
ALTER TABLE openrails.ledger_transfers VALIDATE CONSTRAINT ledger_transfers_currency_shape;
ALTER TABLE openrails.prices VALIDATE CONSTRAINT prices_currency_shape;
ALTER TABLE openrails.tier_schedules VALIDATE CONSTRAINT tier_schedules_currency_shape;
ALTER TABLE openrails.usage_events VALIDATE CONSTRAINT usage_events_currency_shape;
ALTER TABLE openrails.customer_delinquency VALIDATE CONSTRAINT customer_delinquency_currency_shape;
ALTER TABLE openrails.customer_minimum_spend VALIDATE CONSTRAINT customer_minimum_spend_currency_shape;
ALTER TABLE openrails.invoice_items VALIDATE CONSTRAINT invoice_items_currency_shape;
ALTER TABLE openrails.invoice_payments VALIDATE CONSTRAINT invoice_payments_currency_shape;
ALTER TABLE openrails.money_settings VALIDATE CONSTRAINT money_settings_currency_shape;
ALTER TABLE openrails.payments VALIDATE CONSTRAINT payments_currency_shape;
ALTER TABLE openrails.payment_settlement_events VALIDATE CONSTRAINT payment_settlement_events_currency_shape;
ALTER TABLE openrails.checkout_sessions VALIDATE CONSTRAINT checkout_sessions_currency_shape;
ALTER TABLE openrails.grants VALIDATE CONSTRAINT grants_currency_shape;
ALTER TABLE openrails.catalog_credit_balances VALIDATE CONSTRAINT catalog_credit_balances_unit_identity;
ALTER TABLE openrails.products VALIDATE CONSTRAINT products_credit_units_canonical;
ALTER TABLE openrails.subscriptions VALIDATE CONSTRAINT subscriptions_credit_units_canonical;
ALTER TABLE openrails.payments VALIDATE CONSTRAINT payments_credit_units_canonical;
