--
-- $-valued wasted/failed-spend budget windows (#488).
--
-- A new GENERIC, $-denominated per-tier budget lives in the tier_policies.policy
-- JSONB alongside the existing budget_windows (no new column — the policy is one
-- JSONB document):
--
--   policy.bad_spend_windows[] — per-PAYER $-VALUED wasted-spend budget windows:
--     at most LimitMicros of host-reported WASTED $ (a failed attempt that cost
--     the platform money — a hold released without capture, a content-filter
--     reject, an out-of-band failure) per WindowSeconds. Admit denies
--     "abuse_rate_limited" when the payer is over. The per-ACTOR (invoker) wasted
--     budget is a FLAT config default (not stored here — invokers aren't trusted)
--     and admit denies "failure_rate_limited" when the actor is over.
--
-- The wasted-$ running totals themselves are tracked in Redis fixed windows (same
-- infra as throughput), NOT in Postgres — this is a policy-contract doc only.
-- Absent = no per-tier wasted-spend budget (back-compat).
--

COMMENT ON COLUMN openrails.tier_policies.policy IS 'JSONB tier policy: throughput windows, release_windows, queue_limits, entitled_resources, budget_windows, (#487) max_concurrent_held_micros + max_single_charge_micros, and (#488) bad_spend_windows (per-payer $-valued wasted/failed-spend budget windows; admit denies abuse_rate_limited when over). All generic + $-denominated.';
