-- #683: one `rail_` family for everything provider-facing.
--
-- The remote-facing axis was spelled three ways (provider_*, rail_*,
-- external_provider_*), and the two identity tables hid that they are mirror
-- images: rail_merchant_accounts = the MERCHANT's account at a rail (acct_...,
-- NMI Gateway ID, clientAccnum/subacc, recipient wallet);
-- rail_customer_accounts = the CUSTOMER's record at a rail (cus_... —
-- Stripe-only in practice, #682). Every row answers "WHOSE account at WHICH
-- rail". Hard cut, no aliases (#649/#650/#652 discipline).
--
-- Bare "merchant account" / "customer account" (no rail_ prefix) are RESERVED
-- platform-tier nouns for the two-party openrails.com platform; the platform_*
-- family is reserved alongside (see #683).
--
-- Stored merchant-secret NAMES are renamed too (pre-launch hard cut, Paul
-- 2026-07-01): DB-backed names below; Vault-backed deployments must move KV
-- entries provider_accounts/* -> rail_merchant_accounts/* at upgrade (operator
-- step; there are none pre-launch).

-- --- table renames ---
ALTER TABLE openrails.payment_provider_accounts RENAME TO rail_merchant_accounts;
ALTER TABLE openrails.rail_customers RENAME TO rail_customer_accounts;
ALTER TABLE openrails.provider_intents RENAME TO rail_intents;
ALTER TABLE openrails.external_provider_mutation_logs RENAME TO rail_mutation_logs;
ALTER TABLE openrails.provider_refresh_watermarks RENAME TO rail_refresh_watermarks;

-- --- column renames ---
ALTER TABLE openrails.checkout_sessions RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.rail_mutation_logs RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.invoice_payments RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.payment_methods RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.payments RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.rail_intents RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.rail_refresh_watermarks RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.rail_customer_accounts RENAME COLUMN provider_account_id TO rail_merchant_account_id;
ALTER TABLE openrails.subscriptions RENAME COLUMN provider_account_id TO rail_merchant_account_id;
-- symmetric remote-id column: (merchant_id, rail, account_id) in both identity tables
ALTER TABLE openrails.rail_customer_accounts RENAME COLUMN rail_customer_id TO account_id;

-- --- constraint renames (names only; definitions unchanged) ---
ALTER TABLE openrails.checkout_sessions RENAME CONSTRAINT checkout_sessions_provider_account_fk TO checkout_sessions_rail_merchant_account_fk;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_attempt_not_null TO rail_mutation_logs_attempt_not_null;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_created_at_not_null TO rail_mutation_logs_created_at_not_null;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_id_not_null TO rail_mutation_logs_id_not_null;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_merchant_fk TO rail_mutation_logs_merchant_fk;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_merchant_id_not_null TO rail_mutation_logs_merchant_id_not_null;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_phase_check TO rail_mutation_logs_phase_check;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_phase_not_null TO rail_mutation_logs_phase_not_null;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_pkey TO rail_mutation_logs_pkey;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_provider_account_fk TO rail_mutation_logs_rail_merchant_account_fk;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_provider_intent_fk TO rail_mutation_logs_provider_intent_fk;
ALTER TABLE openrails.rail_mutation_logs RENAME CONSTRAINT external_provider_mutation_logs_provider_not_null TO rail_mutation_logs_provider_not_null;
ALTER TABLE openrails.invoice_payments RENAME CONSTRAINT invoice_payments_provider_account_fk TO invoice_payments_rail_merchant_account_fk;
ALTER TABLE openrails.payment_methods RENAME CONSTRAINT payment_methods_provider_account_fk TO payment_methods_rail_merchant_account_fk;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_archived_not_null TO rail_merchant_accounts_archived_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_environment_check TO rail_merchant_accounts_environment_check;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_merchant_fk TO rail_merchant_accounts_merchant_fk;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_nonempty TO rail_merchant_accounts_nonempty;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_owner_check TO rail_merchant_accounts_owner_check;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT payment_provider_accounts_pkey TO rail_merchant_accounts_pkey;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_account_id_not_null TO rail_merchant_accounts_account_id_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_created_at_not_null TO rail_merchant_accounts_created_at_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_environment_not_null TO rail_merchant_accounts_environment_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_first_seen_at_not_null TO rail_merchant_accounts_first_seen_at_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_id_not_null TO rail_merchant_accounts_id_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_merchant_id_not_null TO rail_merchant_accounts_merchant_id_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_owner_not_null TO rail_merchant_accounts_owner_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_provider_type_not_null TO rail_merchant_accounts_provider_type_not_null;
ALTER TABLE openrails.rail_merchant_accounts RENAME CONSTRAINT provider_accounts_updated_at_not_null TO rail_merchant_accounts_updated_at_not_null;
ALTER TABLE openrails.payments RENAME CONSTRAINT payments_provider_account_fk TO payments_rail_merchant_account_fk;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT chk_provider_intents_executed TO chk_rail_intents_executed;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT chk_provider_intents_origin TO chk_rail_intents_origin;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT chk_provider_intents_status TO chk_rail_intents_status;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_attempts_not_null TO rail_intents_attempts_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_created_at_not_null TO rail_intents_created_at_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_id_not_null TO rail_intents_id_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_idempotency_key_not_null TO rail_intents_idempotency_key_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_intent_type_not_null TO rail_intents_intent_type_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_merchant_id_not_null TO rail_intents_merchant_id_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_next_attempt_at_not_null TO rail_intents_next_attempt_at_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_origin_not_null TO rail_intents_origin_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_pkey TO rail_intents_pkey;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_provider_account_fk TO rail_intents_rail_merchant_account_fk;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_provider_not_null TO rail_intents_provider_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_status_not_null TO rail_intents_status_not_null;
ALTER TABLE openrails.rail_intents RENAME CONSTRAINT provider_intents_updated_at_not_null TO rail_intents_updated_at_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_account_nonzero TO rail_refresh_watermarks_account_nonzero;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_created_at_not_null TO rail_refresh_watermarks_created_at_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_event_domain_check TO rail_refresh_watermarks_event_domain_check;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_event_domain_not_null TO rail_refresh_watermarks_event_domain_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_id_not_null TO rail_refresh_watermarks_id_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_identity_key TO rail_refresh_watermarks_identity_key;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_merchant_fk TO rail_refresh_watermarks_merchant_fk;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_merchant_id_not_null TO rail_refresh_watermarks_merchant_id_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_pkey TO rail_refresh_watermarks_pkey;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_provider_account_fk TO rail_refresh_watermarks_rail_merchant_account_fk;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_provider_check TO rail_refresh_watermarks_provider_check;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_provider_not_null TO rail_refresh_watermarks_provider_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_updated_at_not_null TO rail_refresh_watermarks_updated_at_not_null;
ALTER TABLE openrails.rail_refresh_watermarks RENAME CONSTRAINT provider_refresh_watermarks_watermark_at_not_null TO rail_refresh_watermarks_watermark_at_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_created_at_not_null TO rail_customer_accounts_created_at_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_customer_fk TO rail_customer_accounts_customer_fk;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_customer_id_not_null TO rail_customer_accounts_customer_id_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_id_not_null TO rail_customer_accounts_id_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_merchant_id_not_null TO rail_customer_accounts_merchant_id_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_pkey TO rail_customer_accounts_pkey;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_provider_account_fk TO rail_customer_accounts_rail_merchant_account_fk;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_rail_customer_id_not_null TO rail_customer_accounts_rail_customer_id_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_rail_not_null TO rail_customer_accounts_rail_not_null;
ALTER TABLE openrails.rail_customer_accounts RENAME CONSTRAINT rail_customers_updated_at_not_null TO rail_customer_accounts_updated_at_not_null;
ALTER TABLE openrails.subscriptions RENAME CONSTRAINT subscriptions_provider_account_fk TO subscriptions_rail_merchant_account_fk;

-- --- index renames ---
ALTER INDEX openrails.idx_checkout_sessions_provider_account RENAME TO idx_checkout_sessions_rail_merchant_account;
ALTER INDEX openrails.idx_external_provider_mutation_logs_merchant_created RENAME TO idx_rail_mutation_logs_merchant_created;
ALTER INDEX openrails.idx_external_provider_mutation_logs_provider_account RENAME TO idx_rail_mutation_logs_rail_merchant_account;
ALTER INDEX openrails.idx_external_provider_mutation_logs_provider_intent RENAME TO idx_rail_mutation_logs_provider_intent;
ALTER INDEX openrails.idx_external_provider_mutation_logs_provider_phase RENAME TO idx_rail_mutation_logs_provider_phase;
ALTER INDEX openrails.idx_invoice_payments_provider_account RENAME TO idx_invoice_payments_rail_merchant_account;
ALTER INDEX openrails.idx_payment_methods_provider_account RENAME TO idx_payment_methods_rail_merchant_account;
ALTER INDEX openrails.uq_payment_methods_provider_account_instrument RENAME TO uq_payment_methods_rail_merchant_account_instrument;
ALTER INDEX openrails.idx_payment_provider_accounts_merchant RENAME TO idx_rail_merchant_accounts_merchant;
ALTER INDEX openrails.idx_payment_provider_accounts_new_work RENAME TO idx_rail_merchant_accounts_new_work;
ALTER INDEX openrails.uq_payment_provider_accounts_identity RENAME TO uq_rail_merchant_accounts_identity;
ALTER INDEX openrails.idx_payments_provider_account RENAME TO idx_payments_rail_merchant_account;
ALTER INDEX openrails.uq_payments_provider_account_transaction RENAME TO uq_payments_rail_merchant_account_transaction;
ALTER INDEX openrails.idx_provider_intents_due RENAME TO idx_rail_intents_due;
ALTER INDEX openrails.idx_provider_intents_merchant_id RENAME TO idx_rail_intents_merchant_id;
ALTER INDEX openrails.idx_provider_intents_provider_account RENAME TO idx_rail_intents_rail_merchant_account;
ALTER INDEX openrails.idx_provider_intents_subscription RENAME TO idx_rail_intents_subscription;
ALTER INDEX openrails.uq_provider_intents_merchant_idempotency_key RENAME TO uq_rail_intents_merchant_idempotency_key;
ALTER INDEX openrails.idx_provider_refresh_watermarks_account RENAME TO idx_rail_refresh_watermarks_account;
ALTER INDEX openrails.idx_provider_refresh_watermarks_provider RENAME TO idx_rail_refresh_watermarks_provider;
ALTER INDEX openrails.idx_rail_customers_customer RENAME TO idx_rail_customer_accounts_customer;
ALTER INDEX openrails.idx_rail_customers_merchant_id RENAME TO idx_rail_customer_accounts_merchant_id;
ALTER INDEX openrails.idx_rail_customers_provider_account RENAME TO idx_rail_customer_accounts_rail_merchant_account;
ALTER INDEX openrails.uq_rail_customers_customer_provider_account RENAME TO uq_rail_customer_accounts_customer_rail_merchant_account;
ALTER INDEX openrails.uq_rail_customers_customer_rail_legacy RENAME TO uq_rail_customer_accounts_customer_rail_legacy;
ALTER INDEX openrails.uq_rail_customers_merchant_rail_customer_legacy RENAME TO uq_rail_customer_accounts_merchant_rail_customer_legacy;
ALTER INDEX openrails.uq_rail_customers_provider_account_customer RENAME TO uq_rail_customer_accounts_rail_merchant_account_customer;
ALTER INDEX openrails.idx_subscriptions_provider_account RENAME TO idx_subscriptions_rail_merchant_account;
ALTER INDEX openrails.uq_subscriptions_provider_account_subscription RENAME TO uq_subscriptions_rail_merchant_account_subscription;

-- --- stored secret-name prefix (DB-backed store + audit trail) ---
UPDATE openrails.merchant_secrets
   SET name = 'rail_merchant_accounts' || substr(name, length('provider_accounts') + 1)
 WHERE name LIKE 'provider_accounts/%';
UPDATE openrails.merchant_credential_audit
   SET name = 'rail_merchant_accounts' || substr(name, length('provider_accounts') + 1)
 WHERE name LIKE 'provider_accounts/%';
