package contract

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/open-rails/openrails/internal/http/routes"
)

const docsHeader = "<!-- Generated by `go run ./scripts/contracts -write` from the route catalog. Do not edit. -->\n"

var groupTitles = []struct {
	group routes.Group
	title string
	blurb string
}{
	{routes.Meta, "Process", "Health, metrics and capability discovery. Only the standalone server serves the root paths."},
	{routes.Checkout, "Checkout (public)", "What a checkout page needs: the catalog a buyer may see, checkout, checkout sessions."},
	{routes.Customer, "Customer (`/v1/me`)", "A customer acting on its own account."},
	{routes.Merchant, "Merchant", "The merchant API: staff, machines and the Go client alike, each route gated by its merchant permission."},
	{routes.ControlPlane, "Control plane (standalone)", "Merchant accounts, API keys and the team."},
	{routes.Platform, "Platform (standalone)", "The operator tier."},
	{routes.Webhooks, "Provider webhooks", "Inbound provider callbacks."},
}

func (m *model) bodyDoc(v any) string {
	switch body := v.(type) {
	case nil:
		return "—"
	case routes.Stream:
		return "`" + body.ContentType + "`"
	}
	return "`" + m.tsType(reflect.TypeOf(v)) + "`"
}

// routesMD is the route tables: every route by group.
func (m *model) routesMD() []byte {
	var b bytes.Buffer
	b.WriteString(docsHeader)
	b.WriteString("\n# Routes\n\n")
	fmt.Fprintf(&b, "Every route of the HTTP API (%d), from the API root: a standalone server serves them at `/`, an embedded host beneath its mount (usually `/billing`). ", len(m.routes))
	b.WriteString("Request and response names are the schemas of [`api/openapi.json`](../../api/openapi.json), which also lists each route's query parameters and error codes. ")
	b.WriteString("Error codes are in [error-codes.md](error-codes.md).\n\n")
	b.WriteString("**Tier** is what the route checks before its handler: `public` (nothing), `optional` (a user credential when present), `session_id` (the id in the path), `user` (any signed-in user), `customer`, `merchant` (a credential holding the permission on the request's merchant), `operator` (a root-group session), `provider_signature`.\n\n")
	b.WriteString("**Notes**: `when` is the configuration that mounts the route; `scope` the narrowest customer exposure that serves it; `catalog write` a route mounted only where the deployment allows catalog updates; `limit` the per-administrator operation limiter; `Idempotency-Key` a route that reads the header.\n")
	for _, g := range groupTitles {
		var list []routes.Route
		for _, r := range m.routes {
			if r.Group == g.group {
				list = append(list, r)
			}
		}
		if len(list) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", g.title, g.blurb)
		b.WriteString("| Method | Path | Tier | Permission | Request | Response | Notes |\n|---|---|---|---|---|---|---|\n")
		for _, r := range list {
			perm := "—"
			if r.Perm != "" {
				perm = "`" + r.Perm + "`"
				if r.Also != "" {
					perm += " + `" + r.Also + "`"
				}
			}
			var replies []string
			for _, reply := range r.Responses {
				replies = append(replies, fmt.Sprintf("%d %s", reply.Status, m.bodyDoc(reply.Body)))
			}
			var notes []string
			if r.When != routes.Always {
				notes = append(notes, "when `"+string(r.When)+"`")
			}
			if r.Group == routes.Customer && r.Scope != routes.ScopeSelfService {
				notes = append(notes, "scope `"+string(r.Scope)+"`")
			}
			if r.CatalogWrite {
				notes = append(notes, "catalog write")
			}
			if r.Limit != "" {
				notes = append(notes, "limit `"+string(r.Limit)+"`")
			}
			if r.IdempotencyKey {
				notes = append(notes, "`Idempotency-Key`")
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s | %s | %s |\n", r.Method, r.Path, r.Auth, perm, m.bodyDoc(r.Request), strings.Join(replies, "<br>"), strings.Join(notes, "; "))
		}
	}
	return b.Bytes()
}

// errorCodesMD is the error-code table.
func errorCodesMD() []byte {
	var b bytes.Buffer
	b.WriteString(docsHeader)
	b.WriteString("\n# Error codes\n\n")
	b.WriteString("Every `error.code` the API answers, with the HTTP status and `error.type` that always accompany it. Codes are stable; messages are not. ")
	b.WriteString("The registry is `billing.ErrorCodes()`; see [errors.md](errors.md) for the envelope and how clients classify.\n\n")
	b.WriteString("| Code | Status | Type | Meaning |\n|---|---|---|---|\n")
	for _, c := range errorCodes() {
		fmt.Fprintf(&b, "| `%s` | %d | `%s` | %s |\n", c.Code, c.Status, c.Type, c.Meaning)
	}
	return b.Bytes()
}
