package contract

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/open-rails/openrails/internal/http/routes"
)

// RouteSetsFile is openrails' RouteSet constants, generated from the catalog.
const RouteSetsFile = "route_sets.go"

var levelDocs = map[string]string{
	"StaffReads":     "StaffReads is every read of Routes.Merchant: staff looking at customers' billing.",
	"StaffWrites":    "StaffWrites is every write of Routes.Merchant: staff acting on customers' billing.",
	"MerchantConfig": "MerchantConfig is every route of Routes.MerchantConfig, reads included: the merchant's own configuration.",
}

// routeSetsGo renders the RouteSet constants: the level groups, the resource
// groups and one per staff route, named after its Client method.
func routeSetsGo() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./scripts/contracts -write. DO NOT EDIT.\n\npackage openrails\n")
	tiers := []struct {
		tier  int
		title string
	}{
		{routes.TierLevel, "The level groups."},
		{routes.TierResource, "The resource groups: a guard on one overrides its routes' level group."},
		{routes.TierRoute, "One route each, named after its Client method: a guard on one overrides its groups."},
	}
	names := routes.GuardNames()
	for _, t := range tiers {
		fmt.Fprintf(&b, "\n// %s\nconst (\n", t.title)
		for _, g := range names {
			if g.Tier != t.tier {
				continue
			}
			switch t.tier {
			case routes.TierLevel:
				fmt.Fprintf(&b, "\t// %s\n", levelDocs[g.Name])
			case routes.TierResource:
				fmt.Fprintf(&b, "\t// %s covers %s.\n", g.Name, strings.Join(routeNames(g.Routes), ", "))
			case routes.TierRoute:
				fmt.Fprintf(&b, "\t// %s is %s.\n", g.Name, g.Routes[0])
			}
			fmt.Fprintf(&b, "\t%s RouteSet = %q\n", g.Name, string(g.Key))
		}
		b.WriteString(")\n")
	}
	return format.Source(b.Bytes())
}

// routeNames are the Client methods of routes, by key.
func routeNames(keys []string) []string {
	out := make([]string, 0, len(keys))
	for _, key := range keys {
		method, path, _ := strings.Cut(key, " ")
		if r, ok := routes.Lookup(method, path); ok {
			out = append(out, r.Name)
		}
	}
	return out
}
