package contract

import (
	"bytes"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/open-rails/openrails/billing"
	"github.com/open-rails/openrails/internal/http/routes"
)

const tsHeader = "// Generated by `go run ./scripts/contracts -write` from the OpenRails route catalog. Do not edit.\n"

// tsType is t as a TypeScript type.
func (m *model) tsType(t reflect.Type) string {
	t = elem(t)
	k, _ := classify(t)
	switch k {
	case kindString:
		if values := m.enums.of(t); values != nil {
			quoted := make([]string, len(values))
			for i, v := range values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			return strings.Join(quoted, " | ")
		}
		return "string"
	case kindTime:
		return "string"
	case kindInteger, kindNumber:
		return "number"
	case kindBoolean:
		return "boolean"
	case kindAny:
		return "unknown"
	case kindArray:
		return tsElem(m.tsType(t.Elem())) + "[]"
	case kindMap:
		return "Record<string, " + m.tsType(t.Elem()) + ">"
	case kindPage:
		return "ListPage<" + m.tsType(pageItem(t)) + ">"
	}
	return m.names[t]
}

// tsElem parenthesizes a union element type.
func tsElem(s string) string {
	if strings.Contains(s, " | ") {
		return "(" + s + ")"
	}
	return s
}

func tsKey(name string) string {
	for i, r := range name {
		ok := r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

// wireTS is every wire type. A response member is present unless marked
// optional, and null when its Go value is unset; a request-only type's
// members are all optional, since the server reads an omitted one as empty.
func (m *model) wireTS() []byte {
	var b bytes.Buffer
	b.WriteString(tsHeader)
	b.WriteString(`
// One page of a cursor list: next_cursor is null on the last page.
export type ListPage<T> = {
  data: T[]
  next_cursor: string | null
}
`)
	for _, o := range m.sortedObjects() {
		fmt.Fprintf(&b, "\nexport type %s = {\n", o.name)
		for _, f := range o.fields {
			t := m.tsType(f.t)
			if f.quoted {
				t = "string"
			}
			if f.nullable {
				t += " | null"
			}
			opt := ""
			if f.optional || !o.output {
				opt = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s\n", tsKey(f.name), opt, t)
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

// bodyTS names a body's TypeScript type, or null for none.
func (m *model) bodyTS(v any) string {
	switch body := v.(type) {
	case nil:
		return "null"
	case routes.Untyped:
		return `"unknown"`
	case routes.Stream:
		return fmt.Sprintf("%q", body.ContentType)
	}
	return fmt.Sprintf("%q", m.tsType(reflect.TypeOf(v)))
}

// routesTS is the route table: what each route is, who may call it, and the
// names of its request and response types in wire.ts.
func (m *model) routesTS() []byte {
	var b bytes.Buffer
	b.WriteString(tsHeader)
	b.WriteString(`
export type OpenRailsRoute = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE"
  // The path from the API root; a deployment's mount prefix comes before it.
  path: string
  group: string
  auth: string
  permission: string | null
  // The configuration the route needs; null when always mounted.
  mountedWhen: string | null
  // The narrowest customer exposure serving a customer route.
  scope: "self_service" | "billing_management" | "subscription_management" | null
  // wire.ts type names: the JSON body, and each success by status.
  request: string | null
  responses: Readonly<Record<number, string | null>>
  // The route's own codes, and the shared sets (OPENRAILS_ERROR_SETS) it also answers.
  errors: readonly string[]
  errorSets: readonly string[]
}

export const OPENRAILS_ROUTES = [
`)
	sets := map[string][]string{}
	for _, r := range m.routes {
		perm, when, scope := "null", "null", "null"
		if r.Perm != "" {
			perm = fmt.Sprintf("%q", r.Perm)
		}
		if r.When != routes.Always {
			when = fmt.Sprintf("%q", r.When)
		}
		if r.Group == routes.Customer {
			scope = `"self_service"`
			if r.Scope != routes.ScopeSelfService {
				scope = fmt.Sprintf("%q", r.Scope)
			}
		}
		var replies []string
		seen := map[int]bool{}
		for _, reply := range r.Responses {
			if seen[reply.Status] {
				continue // a second body under one status: see openapi.json
			}
			seen[reply.Status] = true
			replies = append(replies, fmt.Sprintf("%d: %s", reply.Status, m.bodyTS(reply.Body)))
		}
		fmt.Fprintf(&b, "  { method: %q, path: %q, group: %q, auth: %q, permission: %s, mountedWhen: %s, scope: %s, request: %s, responses: { %s }, errors: [%s], errorSets: [%s] },\n",
			r.Method, r.Path, r.Group, r.Auth, perm, when, scope, m.bodyTS(r.Request), strings.Join(replies, ", "), quoted(r.Errors), quoted(r.ErrorSets()))
		for _, name := range r.ErrorSets() {
			sets[name] = routes.ErrorSet(name)
		}
	}
	b.WriteString("] as const satisfies readonly OpenRailsRoute[]\n")
	names := make([]string, 0, len(sets))
	for name := range sets {
		names = append(names, name)
	}
	sort.Strings(names)
	b.WriteString("\n// The codes every route of a kind answers, by set name.\nexport const OPENRAILS_ERROR_SETS: Readonly<Record<string, readonly string[]>> = {\n")
	for _, name := range names {
		fmt.Fprintf(&b, "  %q: [%s],\n", name, quoted(sets[name]))
	}
	b.WriteString("}\n")
	b.WriteString("\nexport type OpenRailsRouteKey = `${(typeof OPENRAILS_ROUTES)[number][\"method\"]} ${(typeof OPENRAILS_ROUTES)[number][\"path\"]}`\n")
	return b.Bytes()
}

// errorCodesTS is the error-code registry: every code with its status, type
// and meaning.
func errorCodesTS() []byte {
	codes := errorCodes()
	var b bytes.Buffer
	b.WriteString("// Generated by `go run ./scripts/contracts -write` from billing.ErrorCodes. Do not edit.\n\n")
	b.WriteString("export type OpenRailsErrorCode =\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "  | %q\n", c.Code)
	}
	types := map[string]bool{}
	for _, c := range codes {
		types[c.Type] = true
	}
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, fmt.Sprintf("%q", name))
	}
	sort.Strings(names)
	fmt.Fprintf(&b, "\nexport type OpenRailsErrorType = %s\n", strings.Join(names, " | "))
	b.WriteString("\n// Each code's HTTP status, envelope type and meaning. A message on the wire is\n// diagnostic; classify by code.\nexport const OPENRAILS_ERROR_CODES: Readonly<\n  Record<OpenRailsErrorCode, { status: number; type: OpenRailsErrorType; meaning: string }>\n> = {\n")
	for _, c := range codes {
		meaning, _ := marshal(c.Meaning)
		fmt.Fprintf(&b, "  %s: { status: %d, type: %q, meaning: %s },\n", tsKey(c.Code), c.Status, c.Type, meaning)
	}
	b.WriteString("}\n")
	return b.Bytes()
}

// currenciesTS is the currency scale registry, fixed per OpenRails release.
func currenciesTS() []byte {
	var b bytes.Buffer
	b.WriteString("// Generated by `go run ./scripts/contracts -write` from billing.Currencies. Do not edit.\n\n")
	b.WriteString("// Currency code to native-unit decimals.\nexport const OPENRAILS_CURRENCY_SCALES: Readonly<Record<string, number>> = {\n")
	for _, cur := range billing.Currencies() {
		fmt.Fprintf(&b, "  %s: %d,\n", cur.Code, cur.Decimals)
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func quoted(list []string) string {
	out := make([]string, len(list))
	for i, s := range list {
		out[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(out, ", ")
}
