-- Exact runtime privileges; roles and credentials belong to the host.
GRANT USAGE ON SCHEMA openrails TO :"runtime_user";
GRANT USAGE ON SCHEMA public TO :"runtime_user";
GRANT SELECT ON TABLE public.migrations TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.account_updater_open_batch_merchant_ids(p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.account_updater_work_merchant_ids(p_custodian text, p_environment text, p_now timestamp with time zone, p_default_lookahead_days integer, p_after uuid, p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.count_destructive_intents_by_actor_since(p_actor text, p_intent_types text[], p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.count_destructive_intents_for_merchant_since(p_merchant uuid, p_origins text[], p_intent_types text[], p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.current_merchant_id() TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.custodian_owner_by_identity(p_kind text, p_environment text, p_account_id text) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.customer_merchant_ids_for_subject(p_subject uuid) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.delinquency_work_merchant_ids(p_now timestamp with time zone, p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.due_dunning_merchant_ids(p_rails text[], p_now timestamp with time zone, p_limit integer, p_include_engine boolean) TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.billing_restore_active(uuid) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_merchant_funnel(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_mrr_by_currency(p_exclude uuid) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_rail_health(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_revenue_by_currency(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_weekly_active_merchants(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_weekly_cancelled_subscriptions(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.fleet_weekly_volume(p_exclude uuid, p_since timestamp with time zone) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.lapsed_credit_lot_merchant_ids(p_as_of timestamp with time zone, p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.pending_merchant_secret_cleanups(p_after uuid, p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.psp_owner_by_identity(p_rail text, p_environment text, p_account_id text) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.psp_rail_merchant_ids(p_rails text[], p_limit integer, p_after uuid) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.redrivable_plan_change_merchant_ids(p_limit integer) TO :"runtime_user";
GRANT ALL ON FUNCTION openrails.retention_work_merchant_ids(p_now timestamp with time zone, p_notification_cutoff timestamp with time zone, p_notification_seen_cutoff timestamp with time zone, p_webhook_cutoff timestamp with time zone, p_settlement_cutoff timestamp with time zone, p_lifecycle_cutoff timestamp with time zone, p_after uuid, p_limit integer) TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.destructive_action_switch TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchants TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.metered_rating_watermarks TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.products TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.maintenance_runs TO :"runtime_user";
GRANT UPDATE(finished_at,status,summary,error,affected,reversed_at,reversed_by,note) ON TABLE openrails.maintenance_runs TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.reconciliation_state TO :"runtime_user";
GRANT SELECT,INSERT,DELETE ON TABLE openrails.webhook_events TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.webhook_health TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.webhook_health_daily TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.worker_state TO :"runtime_user";
GRANT SELECT,INSERT,UPDATE ON TABLE openrails.admission_denials_hourly TO :"runtime_user";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE openrails.card_attempt_failures TO :"runtime_user";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE openrails.idempotency_keys TO :"runtime_user";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE openrails.solana_pay_references TO :"runtime_user";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE openrails.solana_pay_receipts TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.billing_policies TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.catalog_meters TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.custodians TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.customers TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.dashboard_configs TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.host_outbox TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.invoices TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.invoker_spend_limits TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.ledger_accounts TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.ledger_transfers TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchant_configurations TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchant_deks TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchant_destructive_policy TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchant_secrets TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.merchant_webhooks TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.notifications TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.prices TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.price_key_movements TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.psps TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.rail_customer_accounts TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.rail_intents TO :"runtime_user";
GRANT SELECT,INSERT,DELETE ON TABLE openrails.rail_mutation_logs TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.rail_refresh_watermarks TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.reconciliation_findings TO :"runtime_user";
GRANT SELECT ON openrails.catalog_drift_events TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.reprice_batches TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.usage_events TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.account_updater_batches TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.billing_policy_bindings TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.catalog_rate_cards TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.customer_delinquency TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.customer_invoice_profiles TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.destructive_run_before_images TO :"runtime_user";
GRANT UPDATE(restored_at) ON TABLE openrails.destructive_run_before_images TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.invoice_items TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.payment_methods TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.custody_migrations TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.subscriptions TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.invoice_payments TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.money_settings TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.solana_subscriptions TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.subscription_reprices TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.subscription_status_transitions TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.subscription_verifications TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.nmi_bulk_checkpoints TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.payments TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.checkout_sessions TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.grants TO :"runtime_user";
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.entitlements TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(state) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(terminal_reference) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(released_at) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(settled_at) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(settlement_provider_cost_usd_micros) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(settlement_rated_usd_micros) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(settlement_body_bytes) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT UPDATE(settlement_body_digest) ON TABLE openrails.operation_authorizations TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(state) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(reason) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(baseline_observation_id) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(qualified_observation_id) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(qualified_provider_cost_usd_micros) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(qualified_at) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT UPDATE(updated_at) ON TABLE openrails.provider_billing_qualifications TO :"runtime_user";
GRANT SELECT,INSERT ON TABLE openrails.provider_billing_observations TO :"runtime_user";
GRANT SELECT ON TABLE openrails.freeloader_episodes TO :"runtime_user";
GRANT SELECT ON TABLE openrails.orphaned_episodes TO :"runtime_user";
GRANT SELECT, INSERT ON openrails.admission_operations TO :"runtime_user";
GRANT UPDATE (expires_at, state, capture_terms, captured_amount, captured_at, released_at) ON openrails.admission_operations TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.financial_held_amount(uuid, uuid, text, timestamptz) TO :"runtime_user";
GRANT SELECT, INSERT, UPDATE, DELETE ON openrails.price_psp_bindings TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.begin_billing_restore(uuid) TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.check_billing_restore_ledger(uuid) TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.finish_billing_restore(uuid,text,bigint) TO :"runtime_user";
GRANT SELECT, INSERT ON TABLE openrails.catalogs TO :"runtime_user";
GRANT UPDATE(updated_at) ON TABLE openrails.catalogs TO :"runtime_user";
GRANT EXECUTE ON FUNCTION openrails.ensure_default_catalog(uuid) TO :"runtime_user";

-- Durable catalog application identities are insert-only.
GRANT SELECT, INSERT ON TABLE openrails.catalog_applications TO :"runtime_user";
GRANT SELECT, INSERT ON TABLE openrails.product_archive_operations TO :"runtime_user";

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE openrails.credential_publications TO :"runtime_user";
GRANT SELECT, INSERT ON TABLE openrails.merchant_configuration_applications TO :"runtime_user";
