// Package schemasnapshot lists the database schema OpenRails v1 freezes:
// every table, column, constraint, index, trigger and function the migrations
// install, read back from the catalogs of a real PostgreSQL. api/schema.txt
// holds the list; go run ./scripts/contracts -write rewrites it and
// TestSchemaSnapshot (ci) fails when it is stale.
package schemasnapshot

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"slices"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/open-rails/openrails/internal/config"
	"github.com/open-rails/openrails/internal/migrate"
	postgresmigrations "github.com/open-rails/openrails/internal/migrate/postgres"
)

const (
	// File is where the list lives, relative to the repository.
	File = "api/schema.txt"
	// PostgresMajor is the server version the list is read from: the catalog
	// functions print definitions differently across major versions.
	PostgresMajor = 18
	// DSNEnv names a disposable PostgreSQL server (the end-to-end suite's).
	DSNEnv = "OPENRAILS_E2E_DSN"
)

// ErrStale reports an api/schema.txt that is not what the migrations install.
var ErrStale = fmt.Errorf("%s is stale: run go run ./scripts/contracts -write with %s naming a disposable PostgreSQL %d server", File, DSNEnv, PostgresMajor)

const header = `# The schema OpenRails' migrations install (internal/migrate/postgres), read
# back from PostgreSQL %d. Generated by go run ./scripts/contracts -write; do
# not edit. Monthly partitions are left out: their names follow the calendar.
`

// Migrations is one line per migration file with its digest. The schema is a
// function of these files, so a list that names them all is current without
// asking a database.
func Migrations() ([]string, error) {
	names, err := fs.Glob(postgresmigrations.FS, "*.up.sql")
	if err != nil {
		return nil, err
	}
	slices.Sort(names)
	lines := make([]string, len(names))
	for i, name := range names {
		body, err := fs.ReadFile(postgresmigrations.FS, name)
		if err != nil {
			return nil, err
		}
		sum := sha256.Sum256(body)
		lines[i] = "migration " + name + " sha256:" + hex.EncodeToString(sum[:])
	}
	return lines, nil
}

// CheckMigrations fails when list was not taken from the current migration
// files. It needs no database; Capture compares the schema itself.
func CheckMigrations(list []byte) error {
	want, err := Migrations()
	if err != nil {
		return err
	}
	var got []string
	for line := range strings.Lines(string(list)) {
		if strings.HasPrefix(line, "migration ") {
			got = append(got, strings.TrimSuffix(line, "\n"))
		}
	}
	if !slices.Equal(got, want) {
		return ErrStale
	}
	return nil
}

// Capture applies the migrations to a scratch database on the server dsn
// names, at the default schema so every name reads as authored, and returns
// the list. The role needs CREATEDB; the scratch database is dropped.
func Capture(ctx context.Context, dsn string) ([]byte, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	admin, err := pgx.ConnectConfig(ctx, cfg.ConnConfig.Copy())
	if err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	defer admin.Close(context.WithoutCancel(ctx))
	var version int
	if err := admin.QueryRow(ctx, `SELECT current_setting('server_version_num')::int / 10000`).Scan(&version); err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	if version != PostgresMajor {
		return nil, fmt.Errorf("schema snapshot: %s is read from PostgreSQL %d; this server is PostgreSQL %d", File, PostgresMajor, version)
	}

	var suffix [6]byte
	_, _ = rand.Read(suffix[:])
	name := "openrails_schema_" + hex.EncodeToString(suffix[:])
	scratch := pgx.Identifier{name}.Sanitize()
	if _, err := admin.Exec(ctx, "CREATE DATABASE "+scratch); err != nil {
		return nil, fmt.Errorf("schema snapshot: create scratch database: %w", err)
	}
	defer func() {
		ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
		defer cancel()
		_, _ = admin.Exec(ctx, "DROP DATABASE IF EXISTS "+scratch+" WITH (FORCE)")
	}()

	cfg.ConnConfig.Database = name
	cfg.MaxConns = 4
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	defer pool.Close()
	if err := migrate.ApplyPostgresMigrations(ctx, pool, migrate.Options{HostRiver: true}); err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}

	// An empty search path makes the catalog functions qualify every name.
	read := cfg.ConnConfig.Copy()
	read.RuntimeParams["search_path"] = "pg_catalog"
	conn, err := pgx.ConnectConfig(ctx, read)
	if err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	defer conn.Close(context.WithoutCancel(ctx))
	list, err := dump(ctx, conn, config.DefaultSchema)
	if err != nil {
		return nil, fmt.Errorf("schema snapshot: %w", err)
	}
	return list, nil
}

// Diff is what differs between two lists, each line under the object it
// belongs to: removed or changed lines of old, then added lines of new.
func Diff(old, new []byte) (gone, added []string) {
	a, b := flatten(old), flatten(new)
	return missing(a, b), missing(b, a)
}

func flatten(list []byte) []string {
	var out []string
	object := ""
	for line := range strings.Lines(string(list)) {
		line = strings.TrimSuffix(line, "\n")
		switch {
		case line == "" || strings.HasPrefix(line, "#"):
		case strings.HasPrefix(line, " "):
			out = append(out, object+": "+strings.TrimSpace(line))
		default:
			object = line
			out = append(out, line)
		}
	}
	return out
}

func missing(from, in []string) []string {
	have := make(map[string]bool, len(in))
	for _, line := range in {
		have[line] = true
	}
	var out []string
	for _, line := range from {
		if !have[line] {
			out = append(out, line)
		}
	}
	return out
}

type relation struct {
	name  string
	lines []string
}

func dump(ctx context.Context, conn *pgx.Conn, schema string) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, header, PostgresMajor)
	migrations, err := Migrations()
	if err != nil {
		return nil, err
	}
	for _, line := range migrations {
		out.WriteString(line + "\n")
	}

	// One row per line of the list: the object it belongs to, then the line.
	section := func(query string, args ...any) ([][2]string, error) {
		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, err
		}
		return pgx.CollectRows(rows, func(row pgx.CollectableRow) (pair [2]string, err error) {
			err = row.Scan(&pair[0], &pair[1])
			return pair, err
		})
	}

	extensions, err := section(`SELECT e.extname, '' FROM pg_extension e WHERE e.extname <> 'plpgsql' ORDER BY 1`)
	if err != nil {
		return nil, err
	}
	for _, e := range extensions {
		out.WriteString("\nextension " + e[0] + "\n")
	}

	// Types the schema declares itself: enums, domains, ranges and composites
	// (a table's row type is the table).
	types, err := section(`
		SELECT format_type(t.oid, NULL),
		       CASE t.typtype
		         WHEN 'e' THEN 'enum ' || (SELECT string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid = t.oid)
		         WHEN 'd' THEN 'domain ' || format_type(t.typbasetype, t.typtypmod) || CASE WHEN t.typnotnull THEN ' NOT NULL' ELSE '' END
		              || COALESCE((SELECT string_agg(' ' || pg_get_constraintdef(c.oid), '' ORDER BY c.conname) FROM pg_constraint c WHERE c.contypid = t.oid), '')
		         WHEN 'r' THEN 'range ' || (SELECT format_type(r.rngsubtype, NULL) FROM pg_range r WHERE r.rngtypid = t.oid)
		         ELSE 'composite ' || (SELECT string_agg(a.attname || ' ' || format_type(a.atttypid, a.atttypmod), ', ' ORDER BY a.attnum) FROM pg_attribute a WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped)
		       END
		  FROM pg_type t
		  JOIN pg_namespace n ON n.oid = t.typnamespace
		  LEFT JOIN pg_class c ON c.oid = t.typrelid
		 WHERE n.nspname = $1 AND t.typtype IN ('e', 'd', 'r', 'c') AND (t.typtype <> 'c' OR c.relkind = 'c')
		 ORDER BY 1`, schema)
	if err != nil {
		return nil, err
	}
	for _, t := range types {
		out.WriteString("\ntype " + t[0] + " " + t[1] + "\n")
	}

	// Tables, partitioned parents included, in name order.
	tables, err := section(`
		SELECT c.oid::regclass::text,
		       CASE c.relpersistence WHEN 'u' THEN ' UNLOGGED' ELSE '' END
		       || COALESCE(' PARTITION BY ' || pg_get_partkeydef(c.oid), '')
		       || COALESCE(' WITH (' || array_to_string(c.reloptions, ', ') || ')', '')
		  FROM pg_class c
		  JOIN pg_namespace n ON n.oid = c.relnamespace
		 WHERE n.nspname = $1 AND c.relkind IN ('r', 'p') AND NOT c.relispartition
		 ORDER BY c.relname`, schema)
	if err != nil {
		return nil, err
	}
	relations := make([]relation, len(tables))
	index := make(map[string]*relation, len(tables))
	for i, t := range tables {
		relations[i] = relation{name: "table " + t[0] + t[1]}
		index[t[0]] = &relations[i]
	}
	for _, query := range []string{
		// Columns in their stored order: it is the order of SELECT * and COPY.
		`SELECT c.oid::regclass::text,
		        'column ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
		        || CASE WHEN a.attcollation <> t.typcollation THEN ' COLLATE ' || a.attcollation::regcollation::text ELSE '' END
		        || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
		        || CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
		                WHEN a.attgenerated = 'v' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') VIRTUAL'
		                WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
		                ELSE '' END
		        || CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY' WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END
		   FROM pg_attribute a
		   JOIN pg_class c ON c.oid = a.attrelid
		   JOIN pg_namespace n ON n.oid = c.relnamespace
		   JOIN pg_type t ON t.oid = a.atttypid
		   LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
		  WHERE n.nspname = $1 AND c.relkind IN ('r', 'p') AND NOT c.relispartition AND a.attnum > 0 AND NOT a.attisdropped
		  ORDER BY c.relname, a.attnum`,
		// NOT NULL is on the column line; a key to a partitioned table repeats
		// itself per partition (conparentid).
		`SELECT c.oid::regclass::text, 'constraint ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid)
		   FROM pg_constraint con
		   JOIN pg_class c ON c.oid = con.conrelid
		   JOIN pg_namespace n ON n.oid = c.relnamespace
		  WHERE n.nspname = $1 AND NOT c.relispartition AND con.contype <> 'n' AND con.conparentid = 0
		  ORDER BY c.relname, con.conname`,
		`SELECT c.oid::regclass::text, 'index ' || pg_get_indexdef(x.indexrelid)
		   FROM pg_index x
		   JOIN pg_class c ON c.oid = x.indrelid
		   JOIN pg_class i ON i.oid = x.indexrelid
		   JOIN pg_namespace n ON n.oid = c.relnamespace
		  WHERE n.nspname = $1 AND NOT c.relispartition
		  ORDER BY c.relname, i.relname`,
		`SELECT c.oid::regclass::text, 'trigger ' || pg_get_triggerdef(tg.oid)
		        || CASE tg.tgenabled WHEN 'O' THEN '' WHEN 'D' THEN ' (disabled)' WHEN 'R' THEN ' (replica)' ELSE ' (always)' END
		   FROM pg_trigger tg
		   JOIN pg_class c ON c.oid = tg.tgrelid
		   JOIN pg_namespace n ON n.oid = c.relnamespace
		  WHERE n.nspname = $1 AND NOT c.relispartition AND NOT tg.tgisinternal
		  ORDER BY c.relname, tg.tgname`,
	} {
		lines, err := section(query, schema)
		if err != nil {
			return nil, err
		}
		for _, line := range lines {
			r := index[line[0]]
			if r == nil {
				return nil, fmt.Errorf("%s belongs to no listed table: %s", line[0], line[1])
			}
			r.lines = append(r.lines, line[1])
		}
	}

	// Everything else the schema holds, each with its whole definition.
	others, err := section(`
		SELECT 'sequence ' || c.oid::regclass::text,
		       format('%s START %s INCREMENT %s MINVALUE %s MAXVALUE %s%s', format_type(s.seqtypid, NULL), s.seqstart, s.seqincrement, s.seqmin, s.seqmax, CASE WHEN s.seqcycle THEN ' CYCLE' ELSE '' END)
		  FROM pg_sequence s
		  JOIN pg_class c ON c.oid = s.seqrelid
		  JOIN pg_namespace n ON n.oid = c.relnamespace
		 WHERE n.nspname = $1
		UNION ALL
		SELECT CASE c.relkind WHEN 'm' THEN 'materialized view ' ELSE 'view ' END || c.oid::regclass::text, pg_get_viewdef(c.oid)
		  FROM pg_class c
		  JOIN pg_namespace n ON n.oid = c.relnamespace
		 WHERE n.nspname = $1 AND c.relkind IN ('v', 'm')
		UNION ALL
		SELECT CASE p.prokind WHEN 'p' THEN 'procedure ' WHEN 'a' THEN 'aggregate ' WHEN 'w' THEN 'window function ' ELSE 'function ' END || p.oid::regprocedure::text,
		       CASE WHEN p.prokind IN ('f', 'p') THEN pg_get_functiondef(p.oid) ELSE 'RETURNS ' || format_type(p.prorettype, NULL) END
		  FROM pg_proc p
		  JOIN pg_namespace n ON n.oid = p.pronamespace
		 WHERE n.nspname = $1
		 ORDER BY 1`, schema)
	if err != nil {
		return nil, err
	}
	for _, o := range others {
		relations = append(relations, relation{name: o[0], lines: strings.Split(o[1], "\n")})
	}

	for _, r := range relations {
		out.WriteString("\n" + r.name + "\n")
		for _, line := range r.lines {
			if line = strings.TrimRight(line, " \t\r"); line != "" {
				out.WriteString("  " + line + "\n")
			}
		}
	}
	return out.Bytes(), nil
}
