package postgresmigrations

// OwnedTables is the reviewed inventory of OpenRails relations. Shared schemas
// are not ownership boundaries; archive and reset checks use this inventory.
var OwnedTables = []string{
	"account_updater_batches",
	"admission_denials_hourly",
	"admission_operations",
	"billing_policies",
	"billing_policy_bindings",
	"card_attempt_failures",
	"catalog_applications",
	"catalog_meters",
	"catalog_rate_cards",
	"catalogs",
	"checkout_sessions",
	"credential_publications",
	"custodians",
	"custody_migrations",
	"customer_delinquency",
	"customer_invoice_profiles",
	"customers",
	"dashboard_configs",
	"destructive_action_switch",
	"destructive_run_before_images",
	"entitlements",
	"grants",
	"host_outbox",
	"idempotency_keys",
	"invoice_items",
	"invoice_payments",
	"invoices",
	"invoker_spend_limits",
	"ledger_accounts",
	"ledger_transfers",
	"maintenance_runs",
	"merchant_configuration_applications",
	"merchant_configurations",
	"merchant_deks",
	"merchant_destructive_policy",
	"merchant_secrets",
	"merchant_webhooks",
	"merchants",
	"metered_rating_watermarks",
	"money_settings",
	"nmi_bulk_checkpoints",
	"notifications",
	"operation_authorizations",
	"payment_methods",
	"payments",
	"price_key_movements",
	"price_psp_bindings",
	"product_archive_operations",
	"prices",
	"products",
	"provider_billing_observations",
	"provider_billing_qualifications",
	"psps",
	"rail_customer_accounts",
	"rail_intents",
	"rail_mutation_logs",
	"rail_refresh_watermarks",
	"reconciliation_findings",
	"reconciliation_state",
	"reprice_batches",
	"solana_pay_receipts",
	"solana_pay_references",
	"solana_subscriptions",
	"subscription_reprices",
	"subscription_status_transitions",
	"subscription_verifications",
	"subscriptions",
	"usage_events",
	"webhook_events",
	"webhook_health",
	"webhook_health_daily",
	"worker_state",
}

// OwnedViews are the OpenRails views which may accompany its tables in an
// exclusive schema. They are not table data and are never archived as rows.
var OwnedViews = []string{"catalog_drift_events", "freeloader_episodes", "orphaned_episodes"}

// OwnedFunctions identifies exact routine signatures; host overloads are not owned.
var OwnedFunctions = []string{
	"account_updater_open_batch_merchant_ids(integer)",
	"account_updater_work_merchant_ids(text, text, timestamp with time zone, integer, uuid, integer)",
	"assign_product_catalog()",
	"begin_billing_restore(uuid)",
	"billing_cycle_label(integer)",
	"billing_restore_active(uuid)",
	"catalog_authored_write()",
	"catalog_price_retired()",
	"catalog_product_offer_state()",
	"check_billing_restore_ledger(uuid)",
	"count_destructive_intents_by_actor_since(text, text[], timestamp with time zone)",
	"count_destructive_intents_for_merchant_since(uuid, text[], text[], timestamp with time zone)",
	"current_merchant_id()",
	"custodian_owner_by_identity(text, text, text)",
	"customer_merchant_ids_for_subject(uuid)",
	"delinquency_work_merchant_ids(timestamp with time zone, integer)",
	"due_dunning_merchant_ids(text[], timestamp with time zone, integer, boolean)",
	"enqueue_payment_settlement_event()",
	"ensure_default_catalog(uuid)",
	"financial_held_amount(uuid, uuid, text, timestamptz)",
	"finish_billing_restore(uuid, text, bigint)",
	"fleet_merchant_funnel(uuid, timestamp with time zone)",
	"fleet_mrr_by_currency(uuid)",
	"fleet_rail_health(uuid, timestamp with time zone)",
	"fleet_revenue_by_currency(uuid, timestamp with time zone)",
	"fleet_weekly_active_merchants(uuid, timestamp with time zone)",
	"fleet_weekly_cancelled_subscriptions(uuid, timestamp with time zone)",
	"fleet_weekly_volume(uuid, timestamp with time zone)",
	"guard_billing_fact_columns()",
	"guard_billing_restore_receipt()",
	"guard_catalog_application_receipt()",
	"guard_catalog_identity()",
	"guard_ledger_account_facts()",
	"guard_merchant_group_binding()",
	"guard_merchant_restore()",
	"guard_product_archive_operation()",
	"guard_product_catalog_identity()",
	"guard_provider_cutover_card()",
	"guard_provider_cutover_intent()",
	"guard_provider_cutover_subscription()",
	"lapsed_credit_lot_merchant_ids(timestamp with time zone, integer)",
	"ledger_transfers_apply_counters()",
	"lock_merchant_configuration_write()",
	"monthly_normalized_amount(bigint, integer)",
	"payment_method_default_candidate(uuid, uuid)",
	"payment_methods_default_usable()",
	"payment_methods_ensure_default()",
	"pending_merchant_secret_cleanups(uuid, integer)",
	"preserve_subscription_collection_policy()",
	"price_interval_label(integer, boolean)",
	"prices_default_key()",
	"products_guard_tier_group()",
	"products_propagate_tier_group()",
	"psp_owner_by_identity(text, text, text)",
	"psp_rail_merchant_ids(text[], integer, uuid)",
	"redrivable_plan_change_merchant_ids(integer)",
	"reject_immutable_billing_fact()",
	"require_finished_billing_restore()",
	"retention_work_merchant_ids(timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone, uuid, integer)",
	"subscriptions_record_status_transition()",
	"subscriptions_set_tier_group()",
}

var OwnedTypes = []string{"payment_status", "subscription_status"}
