// Fixed v2 profiles. New schema fields require an explicit portability decision.
package contract

import "regexp"

var uuidPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

type Column struct {
	Name string
	Type string
}
type Profile struct {
	Name    string
	Columns []Column
}

var Profiles = []Profile{
	{Name: "customers", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"issuer", "text"}, {"created_at", "timestamp with time zone"}, {"last_seen_at", "timestamp with time zone"}}},
	{Name: "custodians", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"key", "text"}, {"kind", "text"}, {"environment", "text"}, {"account_id", "text"}, {"settings", "jsonb"}, {"archived", "boolean"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "catalogs", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"owner_subject", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "merchant_configuration_applications", Columns: []Column{{"merchant_id", "uuid"}, {"application_id", "text"}, {"request_sha256", "bytea"}, {"result", "jsonb"}, {"applied_at", "timestamp with time zone"}}},
	{Name: "catalog_applications", Columns: []Column{{"merchant_id", "uuid"}, {"application_id", "text"}, {"catalog_id", "uuid"}, {"schema_version", "bigint"}, {"request_sha256", "bytea"}, {"base_revision", "bigint"}, {"applied_revision", "bigint"}, {"result", "jsonb"}, {"applied_at", "timestamp with time zone"}}},
	{Name: "products", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"catalog_id", "uuid"}, {"key", "text"}, {"display_name", "text"}, {"description", "text"}, {"entitlements_spec", "jsonb"}, {"tier_group", "character varying(100)"}, {"tier_rank", "integer"}, {"archived", "boolean"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "billing_policies", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"name", "text"}, {"policy", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "catalog_meters", Columns: []Column{{"merchant_id", "uuid"}, {"key", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"event_type", "text"}, {"value_property", "text"}, {"aggregation", "text"}, {"unit", "text"}, {"group_by", "jsonb"}}},
	{Name: "maintenance_runs", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"kind", "text"}, {"actor", "text"}, {"psp_id", "uuid"}, {"mode", "text"}, {"rails", "text[]"}, {"window_since", "timestamp with time zone"}, {"window_until", "timestamp with time zone"}, {"started_at", "timestamp with time zone"}, {"finished_at", "timestamp with time zone"}, {"status", "text"}, {"dry_run", "boolean"}, {"expected_rows", "bigint"}, {"reversed_at", "timestamp with time zone"}, {"reversed_by", "text"}}},
	{Name: "merchant_configurations", Columns: []Column{{"merchant_id", "uuid"}, {"config", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "psps", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"rail", "text"}, {"environment", "text"}, {"account_id", "text"}, {"key", "text"}, {"evidence", "jsonb"}, {"first_seen_at", "timestamp with time zone"}, {"last_verified_at", "timestamp with time zone"}, {"replaced_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"archived", "boolean"}, {"custodian_id", "uuid"}, {"pending_signer_public_key", "text"}}},
	{Name: "reconciliation_state", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"source_domain", "text"}, {"fully_reconciled", "boolean"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "rail_refresh_watermarks", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"rail", "text"}, {"psp_id", "uuid"}, {"event_domain", "text"}, {"watermark_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "prices", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"product_id", "uuid"}, {"amount", "bigint"}, {"currency", "text"}, {"archived", "boolean"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"access_duration_hours", "integer"}, {"auto_renew", "boolean"}, {"trial_unit_amount", "bigint"}, {"trial_duration_hours", "integer"}, {"key", "text"}}},
	{Name: "price_key_movements", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"key", "text"}, {"price_id", "uuid"}, {"effective_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"archived", "boolean"}}},
	{Name: "price_psp_bindings", Columns: []Column{{"merchant_id", "uuid"}, {"price_id", "uuid"}, {"psp_id", "uuid"}, {"plan_id", "text"}, {"price_ref", "text"}, {"recurring_billing_option_id", "text"}, {"plan_pda", "text"}, {"flex_id", "text"}, {"configuration", "jsonb"}}},
	{Name: "billing_policy_bindings", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"tier", "text"}, {"policy_name", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "catalog_rate_cards", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"product_id", "uuid"}, {"ordinal", "integer"}, {"meter_key", "text"}, {"payment_term", "text"}, {"filter", "jsonb"}, {"allowance", "jsonb"}, {"price", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"customer_id", "uuid"}}},
	{Name: "ledger_accounts", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"account_type", "text"}, {"currency", "text"}, {"debits_must_not_exceed_credits", "boolean"}, {"credits_must_not_exceed_debits", "boolean"}, {"credits_posted", "bigint"}, {"debits_posted", "bigint"}, {"created_at", "timestamp with time zone"}}},
	{Name: "invoices", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"currency", "text"}, {"invoice_number", "text"}, {"period_from", "timestamp with time zone"}, {"period_to", "timestamp with time zone"}, {"usage_total", "bigint"}, {"deposits_total", "bigint"}, {"owed_accrued", "bigint"}, {"owed_paid", "bigint"}, {"closing_balance", "bigint"}, {"subtotal_amount", "bigint"}, {"total_amount", "bigint"}, {"amount_paid", "bigint"}, {"amount_due", "bigint"}, {"line_items", "jsonb"}, {"money_movements", "jsonb"}, {"status", "text"}, {"collection_method", "text"}, {"issued_at", "timestamp with time zone"}, {"due_at", "timestamp with time zone"}, {"paid_at", "timestamp with time zone"}, {"voided_at", "timestamp with time zone"}, {"uncollectible_at", "timestamp with time zone"}, {"finalized_at", "timestamp with time zone"}, {"external_invoice_id", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"po_number", "text"}, {"tax", "jsonb"}, {"billing_contacts", "jsonb"}, {"memo", "text"}, {"collection_failure_count", "integer"}, {"collection_failed_at", "timestamp with time zone"}, {"next_collection_attempt_at", "timestamp with time zone"}, {"last_collection_failure_code", "text"}, {"last_collection_failure_message", "text"}, {"collection_intent_id", "uuid"}}},
	{Name: "customer_invoice_profiles", Columns: []Column{{"merchant_id", "uuid"}, {"customer_id", "uuid"}, {"net_terms_days", "integer"}, {"collection_method", "text"}, {"po_number", "text"}, {"tax", "jsonb"}, {"billing_contacts", "jsonb"}, {"memo", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "invoker_spend_limits", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"scope", "text"}, {"scope_key", "text"}, {"windows", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"provenance", "text"}}},
	{Name: "rail_customer_accounts", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"rail", "text"}, {"account_id", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"customer_id", "uuid"}, {"psp_id", "uuid"}}},
	{Name: "payment_methods", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"rail", "character varying(50)"}, {"initial_transaction_id", "character varying(255)"}, {"last_four", "character varying(4)"}, {"card_type", "character varying(50)"}, {"expiry_date", "character varying(5)"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"customer_id", "uuid"}, {"psp_id", "uuid"}, {"rail_customer_ref", "text"}, {"rail_method_ref", "text"}, {"stored_credential_recurring_ref", "text"}, {"stored_credential_unscheduled_ref", "text"}, {"custodian", "text"}, {"custodian_id", "uuid"}, {"fingerprint", "text"}, {"network_token_id", "text"}, {"network_token_status", "text"}, {"network_token_par", "text"}, {"charge_via", "text"}, {"park_reason", "text"}, {"parked_at", "timestamp with time zone"}, {"account_updater_checked_at", "timestamp with time zone"}, {"is_default", "boolean"}}},
	{Name: "reprice_batches", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"price_key", "text"}, {"to_price_id", "uuid"}, {"effective_at", "timestamp with time zone"}, {"subscriptions_matched", "integer"}, {"subscriptions_scheduled", "integer"}, {"subscriptions_skipped", "integer"}, {"created_at", "timestamp with time zone"}, {"kind", "text"}, {"source_price_id", "uuid"}, {"fallback_policy", "text"}, {"subscriptions_blocked", "integer"}}},
	{Name: "subscriptions", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"price_id", "uuid"}, {"product_id", "uuid"}, {"status", "openrails.subscription_status"}, {"rail", "text"}, {"collection_policy", "text"}, {"rail_subscription_id", "text"}, {"user_email", "text"}, {"payment_method_id", "uuid"}, {"current_period_starts_at", "timestamp with time zone"}, {"current_period_ends_at", "timestamp with time zone"}, {"started_at", "timestamp with time zone"}, {"ended_at", "timestamp with time zone"}, {"grace_ends_at", "timestamp with time zone"}, {"scheduled_price_id", "uuid"}, {"last_retry_at", "timestamp with time zone"}, {"retry_attempts", "integer"}, {"next_retry_at", "timestamp with time zone"}, {"cancelled_at", "timestamp with time zone"}, {"cancel_type", "text"}, {"cancel_feedback", "text"}, {"entitlements_spec_snapshot", "jsonb"}, {"gateway_response", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"tier_group", "character varying(100)"}, {"deletion_scheduled_at", "timestamp with time zone"}, {"customer_id", "uuid"}, {"psp_id", "uuid"}, {"deleted_at", "timestamp with time zone"}, {"destructive_run_id", "uuid"}, {"transient_retries", "integer"}, {"dunning_policy", "jsonb"}}},
	{Name: "money_settings", Columns: []Column{{"merchant_id", "uuid"}, {"customer_id", "uuid"}, {"billing_mode", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"tier", "text"}, {"currency", "text"}, {"credit_limit_amount", "bigint"}, {"collection_payment_method_id", "uuid"}}},
	{Name: "payments", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"price_id", "uuid"}, {"rail", "text"}, {"transaction_id", "text"}, {"amount", "bigint"}, {"list_amount", "bigint"}, {"currency", "text"}, {"status", "openrails.payment_status"}, {"subscription_id", "uuid"}, {"refunded_payment_id", "uuid"}, {"discount_code", "text"}, {"discount_reason", "text"}, {"entitlements_spec_snapshot", "jsonb"}, {"metadata", "jsonb"}, {"purchased_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"card_brand", "text"}, {"card_last4", "text"}, {"customer_id", "uuid"}, {"psp_id", "uuid"}, {"attempt_kind", "text"}, {"failure_code", "text"}, {"failure_reason", "text"}, {"reversal_kind", "text"}, {"token_type", "text"}, {"deleted_at", "timestamp with time zone"}, {"destructive_run_id", "uuid"}, {"money_movement", "text"}}},
	{Name: "checkout_sessions", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"price_id", "uuid"}, {"mode", "text"}, {"rail", "text"}, {"status", "text"}, {"amount", "bigint"}, {"currency", "text"}, {"expires_at", "timestamp with time zone"}, {"reference", "text"}, {"transaction_id", "text"}, {"payment_id", "uuid"}, {"subscription_id", "uuid"}, {"rail_fields", "jsonb"}, {"rail_state", "jsonb"}, {"metadata", "jsonb"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"customer_id", "uuid"}, {"psp_id", "uuid"}, {"deleted_at", "timestamp with time zone"}, {"destructive_run_id", "uuid"}, {"routing_reason", "jsonb"}}},
	{Name: "host_outbox", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"event_type", "text"}, {"subject_type", "text"}, {"payment_id", "uuid"}, {"amount", "bigint"}, {"subject_id", "uuid"}, {"currency", "text"}, {"occurred_at", "timestamp with time zone"}, {"data", "jsonb"}, {"delivered_at", "timestamp with time zone"}, {"dedupe_key", "text"}}},
	{Name: "grants", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"product_id", "uuid"}, {"kind", "text"}, {"source_type", "text"}, {"source_id", "text"}, {"payment_id", "uuid"}, {"event", "text"}, {"supersedes_id", "uuid"}, {"spec_snapshot", "jsonb"}, {"starts_at", "timestamp with time zone"}, {"ends_at", "timestamp with time zone"}, {"amount", "bigint"}, {"currency", "text"}, {"reason", "text"}, {"created_at", "timestamp with time zone"}}},
	{Name: "entitlements", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"entitlement", "text"}, {"start_at", "timestamp with time zone"}, {"end_at", "timestamp with time zone"}, {"source_id", "uuid"}, {"source_type", "text"}, {"revoked_at", "timestamp with time zone"}, {"revoke_reason", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"deleted_at", "timestamp with time zone"}, {"customer_id", "uuid"}, {"grant_id", "uuid"}, {"destructive_run_id", "uuid"}}},
	{Name: "ledger_transfers", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"debit_account_id", "uuid"}, {"credit_account_id", "uuid"}, {"amount", "bigint"}, {"currency", "text"}, {"transfer_type", "text"}, {"allow_debit_negative_up_to", "bigint"}, {"source", "text"}, {"source_id", "text"}, {"grant_id", "uuid"}, {"customer_id", "uuid"}, {"invoker_id", "text"}, {"resource", "text"}, {"invoice_id", "uuid"}, {"created_at", "timestamp with time zone"}, {"operation", "text"}}},
	{Name: "usage_events", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"invoker_id", "text"}, {"currency", "text"}, {"resource", "text"}, {"event_type", "text"}, {"dimensions", "jsonb"}, {"amount", "bigint"}, {"source", "text"}, {"source_id", "text"}, {"ledger_transfer_id", "uuid"}, {"pricing_authority", "text"}, {"occurred_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}}},
	{Name: "invoice_items", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"currency", "text"}, {"invoice_id", "uuid"}, {"metadata", "jsonb"}, {"source_type", "text"}, {"source_id", "text"}, {"invoice_at", "timestamp with time zone"}, {"amount", "bigint"}, {"status", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "invoice_payments", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"customer_id", "uuid"}, {"invoice_id", "uuid"}, {"ledger_transfer_id", "uuid"}, {"currency", "text"}, {"amount", "bigint"}, {"status", "text"}, {"rail", "text"}, {"rail_payment_id", "text"}, {"failure_code", "text"}, {"failure_message", "text"}, {"attempted_at", "timestamp with time zone"}, {"settled_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"psp_id", "uuid"}, {"failure_reason", "text"}, {"payment_method_id", "uuid"}, {"idempotency_key", "text"}}},
	{Name: "subscription_reprices", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"subscription_id", "uuid"}, {"from_price_id", "uuid"}, {"to_price_id", "uuid"}, {"effective_at", "timestamp with time zone"}, {"status", "text"}, {"reprice_batch_id", "uuid"}, {"created_at", "timestamp with time zone"}, {"applied_at", "timestamp with time zone"}, {"canceled_at", "timestamp with time zone"}, {"acknowledged_short_notice", "boolean"}, {"kind", "text"}, {"blocked_reason", "text"}}},
	{Name: "subscription_status_transitions", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"subscription_id", "uuid"}, {"from_status", "openrails.subscription_status"}, {"to_status", "openrails.subscription_status"}, {"cancel_type", "text"}, {"occurred_at", "timestamp with time zone"}, {"decision", "text"}, {"from_paid_through", "timestamp with time zone"}, {"to_paid_through", "timestamp with time zone"}}},
	{Name: "solana_subscriptions", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"subscription_id", "uuid"}, {"subscriber_wallet", "text"}, {"authority_pda", "text"}, {"subscription_pda", "text"}, {"plan_pda", "text"}, {"merchant_address", "text"}, {"mint", "text"}, {"plan_created_at_fingerprint", "bigint"}, {"last_pulled_period_start", "timestamp with time zone"}, {"last_signature", "text"}, {"next_pull_at", "timestamp with time zone"}, {"status", "text"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "custody_migrations", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"batch_id", "uuid"}, {"payment_method_id", "uuid"}, {"rail", "text"}, {"from_custodian", "text"}, {"from_custodian_id", "uuid"}, {"from_rail_customer_ref", "text"}, {"from_rail_method_ref", "text"}, {"from_psp_id", "uuid"}, {"to_custodian", "text"}, {"to_custodian_id", "uuid"}, {"to_rail_method_ref", "text"}, {"to_psp_id", "uuid"}, {"exported_at", "timestamp with time zone"}, {"outcome", "text"}, {"reason", "text"}, {"created_at", "timestamp with time zone"}}},
	{Name: "metered_rating_watermarks", Columns: []Column{{"merchant_id", "uuid"}, {"customer_id", "uuid"}, {"currency", "text"}, {"source", "text"}, {"period_from", "timestamp with time zone"}, {"rated_through", "timestamp with time zone"}, {"accrued_amount", "bigint"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "customer_delinquency", Columns: []Column{{"merchant_id", "uuid"}, {"customer_id", "uuid"}, {"currency", "text"}, {"state", "text"}, {"overdue_since", "timestamp with time zone"}, {"entered_at", "timestamp with time zone"}, {"overdue_amount", "bigint"}, {"overdue_invoices", "bigint"}, {"transition_seq", "bigint"}, {"evaluated_at", "timestamp with time zone"}, {"created_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}}},
	{Name: "webhook_events", Columns: []Column{{"merchant_id", "uuid"}, {"op", "text"}, {"event_id", "text"}, {"created_at", "timestamp with time zone"}, {"completed_at", "timestamp with time zone"}}},
	{Name: "rail_intents", Columns: []Column{{"merchant_id", "uuid"}, {"id", "uuid"}, {"rail", "text"}, {"intent_type", "text"}, {"subscription_id", "uuid"}, {"payment_id", "uuid"}, {"price_id", "uuid"}, {"payload", "jsonb"}, {"idempotency_key", "text"}, {"status", "text"}, {"attempts", "integer"}, {"next_attempt_at", "timestamp with time zone"}, {"claimed_until", "timestamp with time zone"}, {"origin", "text"}, {"origin_reason", "text"}, {"actor", "text"}, {"last_failure_reason", "text"}, {"expires_at", "timestamp with time zone"}, {"result_evidence", "jsonb"}, {"created_at", "timestamp with time zone"}, {"executed_at", "timestamp with time zone"}, {"updated_at", "timestamp with time zone"}, {"psp_id", "uuid"}, {"destructive_run_id", "uuid"}, {"custodian_id", "uuid"}}},
	{Name: "admission_operations", Columns: []Column{{"merchant_id", "uuid"}, {"request_id", "text"}, {"payer_id", "uuid"}, {"currency", "text"}, {"estimated_amount", "bigint"}, {"available_amount", "bigint"}, {"terms", "jsonb"}, {"requested_expires_at", "timestamptz"}, {"expires_at", "timestamptz"}, {"admitted_at", "timestamptz"}, {"window_keys", "text[]"}, {"state", "text"}, {"capture_terms", "jsonb"}, {"captured_amount", "bigint"}, {"captured_at", "timestamptz"}, {"released_at", "timestamptz"}}},
}
