-- Issue #232 rollback note.
--
-- This project's ClickHouse migrator (migratekit) is FORWARD-ONLY: it embeds
-- and applies *.up.sql exclusively and never executes *.down.sql. This file
-- exists only to document the (intentionally non-destructive) rollback intent
-- for 005, and is never run automatically.
--
-- A true rollback would have to recreate the pre-005 daily_metrics table and
-- mv_daily_metrics materialized view (keyed by (snapshot_date, currency) only,
-- without tenant_id) — see migration 002 — and drop the tenant_id columns/index
-- added to webhook_events and premium_status_daily. We deliberately do NOT
-- automate dropping daily_metrics here: it is a derived analytics rollup and
-- dropping it would discard tenant-scoped history. Recreate from 002 + 004
-- manually if a rollback is ever required.
